
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author YOSEY
 */
import javax.swing.JOptionPane;
public class satu extends javax.swing.JFrame {

    /**
     * Creates new form satu
     */
    public satu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Nama = new javax.swing.JTextField();
        Gejala = new javax.swing.JComboBox<>();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        Omeprazole = new javax.swing.JRadioButton();
        Sangobion = new javax.swing.JRadioButton();
        Ibuprofen = new javax.swing.JRadioButton();
        Paramex = new javax.swing.JRadioButton();
        Oxycan = new javax.swing.JRadioButton();
        Feminax = new javax.swing.JRadioButton();
        Asamefenamat = new javax.swing.JRadioButton();
        Entrostop = new javax.swing.JRadioButton();
        Sanmol = new javax.swing.JRadioButton();
        Mixagrip = new javax.swing.JRadioButton();
        jPanel7 = new javax.swing.JPanel();
        Exit = new javax.swing.JButton();
        Cetak = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        hasil = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 153, 153));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\YOSEY\\Pictures\\Saved Pictures\\apo.jpg")); // NOI18N
        jLabel4.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jPanel2.add(jLabel4);

        jLabel1.setFont(new java.awt.Font("Baskerville Old Face", 3, 36)); // NOI18N
        jLabel1.setText("APOTEK PASTI SEHAT ");
        jPanel2.add(jLabel1);

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 60));

        jPanel3.setBackground(new java.awt.Color(255, 204, 204));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setText("Nama :");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, -1, -1));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel3.setText("Gejala :");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 60, -1, -1));
        jPanel3.add(Nama, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 10, 280, 37));

        Gejala.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        Gejala.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- PILIH GEJALA --", "Demam", "Asam Lambung", "Sakit Kepala", "Diare", "Sesak Nafas", "Nyeri", "Anemia", "Nyeri Haid", "Sakit Gigi", "Flu dan Batuk" }));
        jPanel3.add(Gejala, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 60, 280, 30));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 800, 110));

        jPanel4.setBackground(new java.awt.Color(255, 153, 153));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 798, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 8, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 800, 10));

        jPanel5.setBackground(new java.awt.Color(255, 153, 153));
        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel5.setForeground(new java.awt.Color(255, 153, 153));
        jPanel5.setLayout(new java.awt.GridLayout(2, 5));

        Omeprazole.setText("Omeprazole");
        Omeprazole.setIcon(new javax.swing.ImageIcon("C:\\Users\\YOSEY\\Pictures\\Saved Pictures\\ome.jpg")); // NOI18N
        Omeprazole.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OmeprazoleActionPerformed(evt);
            }
        });
        jPanel5.add(Omeprazole);

        Sangobion.setText("Sangobion");
        Sangobion.setIcon(new javax.swing.ImageIcon("C:\\Users\\YOSEY\\Pictures\\Saved Pictures\\sango.jpg")); // NOI18N
        Sangobion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SangobionActionPerformed(evt);
            }
        });
        jPanel5.add(Sangobion);

        Ibuprofen.setText("Ibuprofen");
        Ibuprofen.setIcon(new javax.swing.ImageIcon("C:\\Users\\YOSEY\\Pictures\\Saved Pictures\\ibu.jpg")); // NOI18N
        Ibuprofen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IbuprofenActionPerformed(evt);
            }
        });
        jPanel5.add(Ibuprofen);

        Paramex.setText("Paramex");
        Paramex.setIcon(new javax.swing.ImageIcon("C:\\Users\\YOSEY\\Pictures\\Saved Pictures\\param.jpg")); // NOI18N
        Paramex.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ParamexActionPerformed(evt);
            }
        });
        jPanel5.add(Paramex);

        Oxycan.setText("Oxycan");
        Oxycan.setIcon(new javax.swing.ImageIcon("C:\\Users\\YOSEY\\Pictures\\Saved Pictures\\oxy.jpg")); // NOI18N
        Oxycan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OxycanActionPerformed(evt);
            }
        });
        jPanel5.add(Oxycan);

        Feminax.setText("Feminax");
        Feminax.setIcon(new javax.swing.ImageIcon("C:\\Users\\YOSEY\\Pictures\\Saved Pictures\\fem.jpg")); // NOI18N
        Feminax.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FeminaxActionPerformed(evt);
            }
        });
        jPanel5.add(Feminax);

        Asamefenamat.setText("Asamefenamat");
        Asamefenamat.setIcon(new javax.swing.ImageIcon("C:\\Users\\YOSEY\\Pictures\\Saved Pictures\\asame.jpg")); // NOI18N
        Asamefenamat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AsamefenamatActionPerformed(evt);
            }
        });
        jPanel5.add(Asamefenamat);

        Entrostop.setText("Entrostop");
        Entrostop.setIcon(new javax.swing.ImageIcon("C:\\Users\\YOSEY\\Pictures\\Saved Pictures\\entro.jpg")); // NOI18N
        Entrostop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EntrostopActionPerformed(evt);
            }
        });
        jPanel5.add(Entrostop);

        Sanmol.setText("Sanmol");
        Sanmol.setIcon(new javax.swing.ImageIcon("C:\\Users\\YOSEY\\Pictures\\Saved Pictures\\sanmol.jpg")); // NOI18N
        Sanmol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SanmolActionPerformed(evt);
            }
        });
        jPanel5.add(Sanmol);

        Mixagrip.setText("Mixagrip");
        Mixagrip.setIcon(new javax.swing.ImageIcon("C:\\Users\\YOSEY\\Pictures\\grip.jpg")); // NOI18N
        Mixagrip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MixagripActionPerformed(evt);
            }
        });
        jPanel5.add(Mixagrip);

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 800, 220));

        jPanel7.setBackground(new java.awt.Color(255, 204, 204));
        jPanel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel7.setLayout(new java.awt.GridBagLayout());

        Exit.setBackground(new java.awt.Color(255, 102, 102));
        Exit.setText("Exit");
        Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitActionPerformed(evt);
            }
        });
        jPanel7.add(Exit, new java.awt.GridBagConstraints());

        Cetak.setBackground(new java.awt.Color(255, 102, 102));
        Cetak.setText("Cetak");
        Cetak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CetakActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        jPanel7.add(Cetak, gridBagConstraints);

        getContentPane().add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 400, 190, 80));

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 800, -1));

        hasil.setEditable(false);
        hasil.setBackground(new java.awt.Color(255, 153, 153));
        hasil.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        hasil.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(hasil, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 410, 610, 70));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void OmeprazoleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OmeprazoleActionPerformed
        String Gejala =  String.valueOf(satu.Gejala.getSelectedItem());
    if (Omeprazole.isSelected()){
        if(Gejala.equals("--pilih obat")){
        JOptionPane.showMessageDialog(this,"HARAP PILIH GEJALA SEBELUM MELANJUTKAN","DISCLAIMER !!!", JOptionPane.WARNING_MESSAGE);
        }else if(!Gejala.equals("Asam Lambung") ){
        JOptionPane.showMessageDialog(this,"INI BUKAN OBAT UNTUK GEJALA TERSEBUT","DISCLAIMER !!!", JOptionPane.WARNING_MESSAGE);
        Omeprazole.setSelected(false);
        }else{
            JOptionPane.showMessageDialog(this,"Omeprazole adalah obat yang digunakan untuk mengatasi Asam lambung . Harga = Rp. 22.000/strip(10 kaplet)","Omeprazole", JOptionPane.INFORMATION_MESSAGE);
        }
    }   // TODO add your handling code here:
    }//GEN-LAST:event_OmeprazoleActionPerformed

    private void SangobionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SangobionActionPerformed
        String Gejala;
        Gejala = String.valueOf(satu.Gejala.getSelectedItem());
    if (Sangobion.isSelected()){
        if(Gejala.equals("--pilih obat")){
        JOptionPane.showMessageDialog(this,"HARAP PILIH GEJALA SEBELUM MELANJUTKAN","DISCLAIMER !!!", JOptionPane.WARNING_MESSAGE);
        }else if(!Gejala.equals("Anemia") ){
        JOptionPane.showMessageDialog(this,"INI BUKAN OBAT UNTUK GEJALA TERSEBUT","DISCLAIMER !!!", JOptionPane.WARNING_MESSAGE);
        Sangobion.setSelected(false);
        }else{
            JOptionPane.showMessageDialog(this,"Sangobion merupakan obat yang dapat digunakan untuk menambah darah, Sangobion tablet 500mg . Harga = Rp. 12.000/strip(10 kaplet)","Sangobion", JOptionPane.INFORMATION_MESSAGE);
        }
      }           
    }//GEN-LAST:event_SangobionActionPerformed

    private void IbuprofenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IbuprofenActionPerformed
        String Gejala;
        Gejala = String.valueOf(satu.Gejala.getSelectedItem());
    if (Ibuprofen.isSelected()){
        if(Gejala.equals("--pilih obat")){
        JOptionPane.showMessageDialog(this,"HARAP PILIH GEJALA SEBELUM MELANJUTKAN","DISCLAIMER !!!", JOptionPane.WARNING_MESSAGE);
        }else if(!Gejala.equals("Nyeri") ){
        JOptionPane.showMessageDialog(this,"INI BUKAN OBAT UNTUK GEJALA TERSEBUT","DISCLAIMER !!!", JOptionPane.WARNING_MESSAGE);
        Ibuprofen.setSelected(false);
        }else{
            JOptionPane.showMessageDialog(this,"Ibuprofen merupakan obat yang dapat digunakan untuk meredakan nyeri, Ibuprofen tablet 500mg . Harga = Rp. 7.000/strip(10 kaplet)","Ibuprofen", JOptionPane.INFORMATION_MESSAGE);
        }
      }           // TODO add your handling code here:
    }//GEN-LAST:event_IbuprofenActionPerformed

    private void ParamexActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ParamexActionPerformed
        String Gejala;
        Gejala = String.valueOf(satu.Gejala.getSelectedItem());
    if (Paramex.isSelected()){
        if(Gejala.equals("--pilih obat")){
        JOptionPane.showMessageDialog(this,"HARAP PILIH GEJALA SEBELUM MELANJUTKAN","DISCLAIMER !!!", JOptionPane.WARNING_MESSAGE);
        }else if(!Gejala.equals("Sakit Kepala") ){
        JOptionPane.showMessageDialog(this,"INI BUKAN OBAT UNTUK GEJALA TERSEBUT","DISCLAIMER !!!", JOptionPane.WARNING_MESSAGE);
        Paramex.setSelected(false);
        }else{
            JOptionPane.showMessageDialog(this,"Paramex merupakan obat yang dapat digunakan untuk meredakan sakit kepala, Paramex tablet 500mg . Harga = Rp. 5.000/strip(4 kaplet)","Paramex", JOptionPane.INFORMATION_MESSAGE);
        }
      }      // TODO add your handling code here:
    }//GEN-LAST:event_ParamexActionPerformed

    private void OxycanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OxycanActionPerformed
       String Gejala;
        Gejala = String.valueOf(satu.Gejala.getSelectedItem());
    if (Oxycan.isSelected()){
        if(Gejala.equals("--pilih obat")){
        JOptionPane.showMessageDialog(this,"HARAP PILIH GEJALA SEBELUM MELANJUTKAN","DISCLAIMER !!!", JOptionPane.WARNING_MESSAGE);
        }else if(!Gejala.equals("Sesak Nafas") ){
        JOptionPane.showMessageDialog(this,"INI BUKAN OBAT UNTUK GEJALA TERSEBUT","DISCLAIMER !!!", JOptionPane.WARNING_MESSAGE);
        Oxycan.setSelected(false);
        }else{
            JOptionPane.showMessageDialog(this,"Oxycan merupakan obat yang dapat digunakan untuk meredakan sesak nafas, Oxycan tablet 500mg . Harga = Rp. 50.000/strip(1 tabung)","Oxycan", JOptionPane.INFORMATION_MESSAGE);
        }
      }      // TODO add your handling code here:
    }//GEN-LAST:event_OxycanActionPerformed

    private void FeminaxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FeminaxActionPerformed
        String Gejala;
        Gejala = String.valueOf(satu.Gejala.getSelectedItem());
    if (Feminax.isSelected()){
        if(Gejala.equals("--pilih obat")){
        JOptionPane.showMessageDialog(this,"HARAP PILIH GEJALA SEBELUM MELANJUTKAN","DISCLAIMER !!!", JOptionPane.WARNING_MESSAGE);
        }else if(!Gejala.equals("Nyeri Haid") ){
        JOptionPane.showMessageDialog(this,"INI BUKAN OBAT UNTUK GEJALA TERSEBUT","DISCLAIMER !!!", JOptionPane.WARNING_MESSAGE);
        Feminax.setSelected(false);
        }else{
            JOptionPane.showMessageDialog(this,"Feminax merupakan obat yang dapat digunakan untuk meredakan nyeri perut saat haid, Feminax tablet 500mg . Harga = Rp. 5.000/strip(4 kaplet)","Feminax", JOptionPane.INFORMATION_MESSAGE);
        }
      }   // TODO add your handling code here:
    }//GEN-LAST:event_FeminaxActionPerformed

    private void AsamefenamatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AsamefenamatActionPerformed
        String Gejala;
        Gejala = String.valueOf(satu.Gejala.getSelectedItem());
    if (Asamefenamat.isSelected()){
        if(Gejala.equals("--pilih obat")){
        JOptionPane.showMessageDialog(this,"HARAP PILIH GEJALA SEBELUM MELANJUTKAN","DISCLAIMER !!!", JOptionPane.WARNING_MESSAGE);
        }else if(!Gejala.equals("Sakit Gigi") ){
        JOptionPane.showMessageDialog(this,"INI BUKAN OBAT UNTUK GEJALA TERSEBUT","DISCLAIMER !!!", JOptionPane.WARNING_MESSAGE);
        Asamefenamat.setSelected(false);
        }else{
            JOptionPane.showMessageDialog(this,"Asamefenamat merupakan obat yang dapat digunakan untuk meredakan nyeri sakit gigi, Asamefenamat tablet 500mg . Harga = Rp. 7.000/strip(10 kaplet)","Asamefenamat", JOptionPane.INFORMATION_MESSAGE);
        }
      } // TODO add your handling code here:
    }//GEN-LAST:event_AsamefenamatActionPerformed

    private void EntrostopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EntrostopActionPerformed
        String Gejala;
        Gejala = String.valueOf(satu.Gejala.getSelectedItem());
    if (Entrostop.isSelected()){
        if(Gejala.equals("--pilih obat")){
        JOptionPane.showMessageDialog(this,"HARAP PILIH GEJALA SEBELUM MELANJUTKAN","DISCLAIMER !!!", JOptionPane.WARNING_MESSAGE);
        }else if(!Gejala.equals("Diare") ){
        JOptionPane.showMessageDialog(this,"INI BUKAN OBAT UNTUK GEJALA TERSEBUT","DISCLAIMER !!!", JOptionPane.WARNING_MESSAGE);
        Entrostop.setSelected(false);
        }else{
            JOptionPane.showMessageDialog(this,"Entrostop merupakan obat yang dapat digunakan untuk diare, Entrostop tablet 500mg . Harga = Rp. 10.000/strip(10 kaplet)","Entrostop", JOptionPane.INFORMATION_MESSAGE);
        }
      }// TODO add your handling code here:
    }//GEN-LAST:event_EntrostopActionPerformed

    private void SanmolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SanmolActionPerformed
        String Gejala;
        Gejala = String.valueOf(satu.Gejala.getSelectedItem());
    if (Sanmol.isSelected()){
        if(Gejala.equals("--pilih obat")){
        JOptionPane.showMessageDialog(this,"HARAP PILIH GEJALA SEBELUM MELANJUTKAN","DISCLAIMER !!!", JOptionPane.WARNING_MESSAGE);
        }else if(!Gejala.equals("Demam") ){
        JOptionPane.showMessageDialog(this,"INI BUKAN OBAT UNTUK GEJALA TERSEBUT","DISCLAIMER !!!", JOptionPane.WARNING_MESSAGE);
        Sanmol.setSelected(false);
        }else{
            JOptionPane.showMessageDialog(this,"Sanmol merupakan obat yang dapat digunakan untuk deman, Sanmol tablet 500mg . Harga = Rp. 10.000/strip(10 kaplet)","Sanmol", JOptionPane.INFORMATION_MESSAGE);
        }
      }// TODO add your handling code here:
    }//GEN-LAST:event_SanmolActionPerformed

    private void CetakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CetakActionPerformed
        double Harga = 0;
    String Obat = "";
    String Gejala = String.valueOf(satu.Gejala.getSelectedItem());
    String name = Nama.getText();

    if (Omeprazole.isSelected()) {
        Harga += 22000;
        Obat += "Omeprazole\n";
    }
    if (Sangobion.isSelected()) {
        Harga += 12000;
        Obat += "Sangobion\n";
    }
    if (Ibuprofen.isSelected()) {
        Harga += 10000;
        Obat += "Ibuprofen\n";
    }
    if (Paramex.isSelected()) {
        Harga += 5000;
        Obat += "Paramex\n";
    }
    if (Oxycan.isSelected()) {
        Harga += 50000;
        Obat += "Oxycan\n";
    }
    if (Feminax.isSelected()) {
        Harga += 5000;
        Obat += "Feminax\n";
    }
    if (Asamefenamat.isSelected()) {
        Harga += 7000;
        Obat += "Asamefenamat\n";
    }
    if (Entrostop.isSelected()) {
        Harga += 10000;
        Obat += "Entrostop\n";
    }
    if (Sanmol.isSelected()) {
        Harga += 10000;
        Obat += "Sanmol\n";
    }
    if (Mixagrip.isSelected()) {
        Harga += 4000;
        Obat += "Mixagrip\n";
    }
    
    if (Gejala.equals("") || Obat.isEmpty() || name.isEmpty()) {
        JOptionPane.showMessageDialog(this,"Anda belum memilih dengan benar, tolong diisi secara keseluruhan","SILAHKAN MENGISI FORM !", JOptionPane.WARNING_MESSAGE);
    }
    else {
        hasil.setText("Nama = "+ Nama .getText() + " || Gejala = " + Gejala + " || Obat = " + Obat + " || Total Harga : Rp. " + Harga);
    }// TODO add your handling code here:
    }//GEN-LAST:event_CetakActionPerformed

    private void ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitActionPerformed
        this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_ExitActionPerformed

    private void MixagripActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MixagripActionPerformed
        String Gejala;
        Gejala = String.valueOf(satu.Gejala.getSelectedItem());
    if (Mixagrip.isSelected()){
        if(Gejala.equals("--pilih obat")){
        JOptionPane.showMessageDialog(this,"HARAP PILIH GEJALA SEBELUM MELANJUTKAN","DISCLAIMER !!!", JOptionPane.WARNING_MESSAGE);
        }else if(!Gejala.equals("Flu dan Batuk") ){
        JOptionPane.showMessageDialog(this,"INI BUKAN OBAT UNTUK GEJALA TERSEBUT","DISCLAIMER !!!", JOptionPane.WARNING_MESSAGE);
        Mixagrip.setSelected(false);
        }else{
            JOptionPane.showMessageDialog(this,"Mixagrip merupakan obat yang dapat digunakan untuk Flu dan Batuk, Mixagrip tablet 500mg . Harga = Rp. 4.000/strip(4 kaplet)","Mixagrip", JOptionPane.INFORMATION_MESSAGE);
        }
      }// TODO add your handling code here:
    }//GEN-LAST:event_MixagripActionPerformed

    /**
     * @param args the command line arguments
     */
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new satu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton Asamefenamat;
    private javax.swing.JButton Cetak;
    private javax.swing.JRadioButton Entrostop;
    private javax.swing.JButton Exit;
    private javax.swing.JRadioButton Feminax;
    private static javax.swing.JComboBox<String> Gejala;
    private javax.swing.JRadioButton Ibuprofen;
    private javax.swing.JRadioButton Mixagrip;
    private javax.swing.JTextField Nama;
    private javax.swing.JRadioButton Omeprazole;
    private javax.swing.JRadioButton Oxycan;
    private javax.swing.JRadioButton Paramex;
    private javax.swing.JRadioButton Sangobion;
    private javax.swing.JRadioButton Sanmol;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField hasil;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    // End of variables declaration//GEN-END:variables
}
