/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package crud;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author EBC KOMPUTER
 */
public class App extends javax.swing.JFrame {

    Connection conn;
    
    public App() {
        initComponents();
        conn = koneksi.getConnection();        
        loadDataKaryawan();
        loadDataProyek();
        loadDataTransaksi();
    }
    
    private void reset(){
        tfTK_Nama.setText("");
        tfTK_Jabatan.setText("");
        tfTK_Departemen.setText("");
        tfEK_Id.setText("");
        tfEK_Nama.setText("");
        tfEK_Jabatan.setText("");
        tfEK_Departemen.setText("");
        tfHK_Id.setText("");
        
        tfTP_NamaProyek.setText("");
        tfTP_DurasiPengerjaan.setText("");
        tfEP_Id.setText("");
        tfEP_NamaProyek.setText("");
        tfEP_DurasiPengerjaan.setText("");
        tfHP_Id.setText("");
        
    }
    
    private void resetTransaksi(){
        tfTT_Peran.setText("");
        tfET_Id.setText("");
        cbTT_Karyawan.removeAllItems();
        cbTT_Proyek.removeAllItems();
        cbET_Karyawan.removeAllItems();
        cbET_Proyek.removeAllItems();
        tfET_Peran.setText("");
        tfHT_Id.setText("");
    }
    
    private void loadDataKaryawan(){
        DefaultTableModel model = (DefaultTableModel) TbKaryawan.getModel();
        model.setRowCount(0);
        
        try {
            String sql = "SELECT * FROM karyawan";
            PreparedStatement ps = conn.prepareStatement(sql);
            ResultSet rs = ps.executeQuery();
            while(rs.next()){
                model.addRow(new Object[]{
                   rs.getInt("id"),
                   rs.getString("nama"),
                   rs.getString("jabatan"),
                   rs.getString("departemen")
                });
            }
            
        } catch (SQLException e) {
            System.out.println("Error Save Data " + e.getMessage());
        }
    }
    
    private void loadDataProyek(){
        DefaultTableModel model = (DefaultTableModel) TbProyek.getModel();
        model.setRowCount(0);
        
        try {
            String sql = "SELECT * FROM proyek";
            PreparedStatement ps = conn.prepareStatement(sql);
            ResultSet rs = ps.executeQuery();
            while(rs.next()){
                model.addRow(new Object[]{
                   rs.getInt("id"),
                   rs.getString("nama_proyek"),
                   rs.getString("durasi_pengerjaan")
                });
            }
            
        } catch (SQLException e) {
            System.out.println("Error Save Data " + e.getMessage());
        }
    }
    
    private void loadDataTransaksi(){
        DefaultTableModel model = (DefaultTableModel) TbTransaksi.getModel();
        model.setRowCount(0);
        
        try {
            String sql = "SELECT * FROM transaksi";
            PreparedStatement ps = conn.prepareStatement(sql);
            ResultSet rs = ps.executeQuery();
            while(rs.next()){
                model.addRow(new Object[]{
                   rs.getInt("id"),
                   rs.getInt("id_karyawan"),
                   rs.getString("id_proyek"),
                   rs.getString("peran")
                });
            }
            
        } catch (SQLException e) {
            System.out.println("Error Save Data " + e.getMessage());
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        btnEditKaryawan = new javax.swing.JButton();
        btnHapusKaryawan = new javax.swing.JButton();
        btnTambahKaryawan = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jInternalFrame1 = new javax.swing.JInternalFrame();
        jPanel15 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        tfTK_Nama = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        tfTK_Jabatan = new javax.swing.JTextField();
        tfTK_Departemen = new javax.swing.JTextField();
        btnTK_Simpan = new javax.swing.JButton();
        jInternalFrame4 = new javax.swing.JInternalFrame();
        jPanel24 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        tfEK_Id = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        tfEK_Nama = new javax.swing.JTextField();
        tfEK_Jabatan = new javax.swing.JTextField();
        btnEK_Simpan = new javax.swing.JButton();
        jLabel22 = new javax.swing.JLabel();
        tfEK_Departemen = new javax.swing.JTextField();
        jInternalFrame5 = new javax.swing.JInternalFrame();
        jPanel25 = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        tfHK_Id = new javax.swing.JTextField();
        btnHK_Hapus = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TbKaryawan = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jPanel16 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jPanel17 = new javax.swing.JPanel();
        btnEditProyek = new javax.swing.JButton();
        btnHapusProyek = new javax.swing.JButton();
        btnTambahProyek = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        jInternalFrame6 = new javax.swing.JInternalFrame();
        jPanel26 = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        tfTP_NamaProyek = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        tfTP_DurasiPengerjaan = new javax.swing.JTextField();
        btnTP_Simpan = new javax.swing.JButton();
        jInternalFrame7 = new javax.swing.JInternalFrame();
        jPanel27 = new javax.swing.JPanel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        tfEP_Id = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        tfEP_NamaProyek = new javax.swing.JTextField();
        tfEP_DurasiPengerjaan = new javax.swing.JTextField();
        btnEP_Simpan = new javax.swing.JButton();
        jInternalFrame8 = new javax.swing.JInternalFrame();
        jPanel28 = new javax.swing.JPanel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        tfHP_Id = new javax.swing.JTextField();
        btnHP_Hapus = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        TbProyek = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        jPanel20 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jPanel21 = new javax.swing.JPanel();
        btnEditTransaksi = new javax.swing.JButton();
        btnHapusTransaksi = new javax.swing.JButton();
        btnTambahTransaksi = new javax.swing.JButton();
        jPanel10 = new javax.swing.JPanel();
        jInternalFrame9 = new javax.swing.JInternalFrame();
        jPanel32 = new javax.swing.JPanel();
        jLabel47 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        tfTT_Peran = new javax.swing.JTextField();
        cbTT_Karyawan = new javax.swing.JComboBox<>();
        cbTT_Proyek = new javax.swing.JComboBox<>();
        btnTT_Simpan = new javax.swing.JButton();
        jInternalFrame10 = new javax.swing.JInternalFrame();
        jPanel33 = new javax.swing.JPanel();
        jLabel51 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        jLabel53 = new javax.swing.JLabel();
        jLabel54 = new javax.swing.JLabel();
        btnET_Simpan = new javax.swing.JButton();
        cbET_Karyawan = new javax.swing.JComboBox<>();
        cbET_Proyek = new javax.swing.JComboBox<>();
        jLabel58 = new javax.swing.JLabel();
        tfET_Peran = new javax.swing.JTextField();
        tfET_Id = new javax.swing.JTextField();
        jInternalFrame11 = new javax.swing.JInternalFrame();
        jPanel34 = new javax.swing.JPanel();
        jLabel55 = new javax.swing.JLabel();
        jLabel56 = new javax.swing.JLabel();
        btnHT_Hapus = new javax.swing.JButton();
        tfHT_Id = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        TbTransaksi = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Manajemen Karyawan dan Proyek");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(166, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(146, 146, 146))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jTabbedPane1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jPanel3.setLayout(new java.awt.BorderLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Tabel Karyawan");
        jPanel6.add(jLabel2);

        jPanel3.add(jPanel6, java.awt.BorderLayout.PAGE_START);

        jPanel7.setLayout(new java.awt.GridBagLayout());

        btnEditKaryawan.setText("Edit");
        btnEditKaryawan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditKaryawanActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(35, 18, 35, 0);
        jPanel7.add(btnEditKaryawan, gridBagConstraints);

        btnHapusKaryawan.setText("Hapus");
        btnHapusKaryawan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusKaryawanActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(35, 18, 35, 184);
        jPanel7.add(btnHapusKaryawan, gridBagConstraints);

        btnTambahKaryawan.setText("Tambah");
        btnTambahKaryawan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahKaryawanActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(35, 165, 35, 0);
        jPanel7.add(btnTambahKaryawan, gridBagConstraints);

        jPanel3.add(jPanel7, java.awt.BorderLayout.PAGE_END);

        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jInternalFrame1.setClosable(true);
        jInternalFrame1.setVisible(false);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Tambah Data Karyawan");

        jLabel6.setText("Nama");

        jLabel7.setText("Jabatan");

        jLabel8.setText("Departemen");

        btnTK_Simpan.setText("Simpan");
        btnTK_Simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTK_SimpanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel15Layout.createSequentialGroup()
                .addContainerGap(91, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(98, 98, 98))
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel15Layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(tfTK_Nama, javax.swing.GroupLayout.DEFAULT_SIZE, 217, Short.MAX_VALUE)
                            .addComponent(tfTK_Jabatan)
                            .addComponent(tfTK_Departemen)))
                    .addGroup(jPanel15Layout.createSequentialGroup()
                        .addGap(138, 138, 138)
                        .addComponent(btnTK_Simpan)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel5)
                .addGap(24, 24, 24)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfTK_Nama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfTK_Jabatan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfTK_Departemen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnTK_Simpan)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addComponent(jPanel15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel8.add(jInternalFrame1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 30, 360, -1));

        jInternalFrame4.setClosable(true);
        jInternalFrame4.setVisible(false);

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel13.setText("Edit Data Karyawan");

        jLabel19.setText("ID");

        jLabel20.setText("Nama *(data baru)");

        jLabel21.setText("Jabatan *(data baru)");

        btnEK_Simpan.setText("Simpan");
        btnEK_Simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEK_SimpanActionPerformed(evt);
            }
        });

        jLabel22.setText("Departemen *(data baru)");

        javax.swing.GroupLayout jPanel24Layout = new javax.swing.GroupLayout(jPanel24);
        jPanel24.setLayout(jPanel24Layout);
        jPanel24Layout.setHorizontalGroup(
            jPanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel24Layout.createSequentialGroup()
                .addGap(0, 113, Short.MAX_VALUE)
                .addComponent(jLabel13)
                .addGap(105, 105, 105))
            .addGroup(jPanel24Layout.createSequentialGroup()
                .addGroup(jPanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel24Layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addGroup(jPanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel22)
                            .addComponent(jLabel19)
                            .addComponent(jLabel20)
                            .addComponent(jLabel21)
                            .addComponent(tfEK_Id, javax.swing.GroupLayout.DEFAULT_SIZE, 217, Short.MAX_VALUE)
                            .addComponent(tfEK_Nama)
                            .addComponent(tfEK_Jabatan)
                            .addComponent(tfEK_Departemen)))
                    .addGroup(jPanel24Layout.createSequentialGroup()
                        .addGap(132, 132, 132)
                        .addComponent(btnEK_Simpan)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel24Layout.setVerticalGroup(
            jPanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel24Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel13)
                .addGap(18, 18, 18)
                .addComponent(jLabel19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfEK_Id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel20)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfEK_Nama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel21)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfEK_Jabatan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel22)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfEK_Departemen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnEK_Simpan)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jInternalFrame4Layout = new javax.swing.GroupLayout(jInternalFrame4.getContentPane());
        jInternalFrame4.getContentPane().setLayout(jInternalFrame4Layout);
        jInternalFrame4Layout.setHorizontalGroup(
            jInternalFrame4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel24, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jInternalFrame4Layout.setVerticalGroup(
            jInternalFrame4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel24, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel8.add(jInternalFrame4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 0, 360, -1));

        jInternalFrame5.setClosable(true);
        jInternalFrame5.setVisible(false);

        jLabel23.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel23.setText("Hapus Data Karyawan");

        jLabel24.setText("ID");

        btnHK_Hapus.setText("Hapus");
        btnHK_Hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHK_HapusActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel25Layout = new javax.swing.GroupLayout(jPanel25);
        jPanel25.setLayout(jPanel25Layout);
        jPanel25Layout.setHorizontalGroup(
            jPanel25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel25Layout.createSequentialGroup()
                .addGroup(jPanel25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel25Layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addGroup(jPanel25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel24)
                            .addComponent(tfHK_Id, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel25Layout.createSequentialGroup()
                        .addGap(129, 129, 129)
                        .addComponent(btnHK_Hapus))
                    .addGroup(jPanel25Layout.createSequentialGroup()
                        .addGap(98, 98, 98)
                        .addComponent(jLabel23)))
                .addContainerGap(68, Short.MAX_VALUE))
        );
        jPanel25Layout.setVerticalGroup(
            jPanel25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel25Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel23)
                .addGap(18, 18, 18)
                .addComponent(jLabel24)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfHK_Id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnHK_Hapus)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jInternalFrame5Layout = new javax.swing.GroupLayout(jInternalFrame5.getContentPane());
        jInternalFrame5.getContentPane().setLayout(jInternalFrame5Layout);
        jInternalFrame5Layout.setHorizontalGroup(
            jInternalFrame5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel25, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jInternalFrame5Layout.setVerticalGroup(
            jInternalFrame5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel25, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel8.add(jInternalFrame5, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 0, 360, -1));

        TbKaryawan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Nama", "Jabatan", "Departemen"
            }
        ));
        jScrollPane1.setViewportView(TbKaryawan);
        if (TbKaryawan.getColumnModel().getColumnCount() > 0) {
            TbKaryawan.getColumnModel().getColumn(0).setResizable(false);
        }

        jPanel8.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 602, 372));

        jPanel3.add(jPanel8, java.awt.BorderLayout.CENTER);

        jTabbedPane1.addTab("Karyawan", jPanel3);

        jPanel4.setLayout(new java.awt.BorderLayout());

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setText("Tabel Proyek");
        jPanel16.add(jLabel9);

        jPanel4.add(jPanel16, java.awt.BorderLayout.PAGE_START);

        jPanel17.setLayout(new java.awt.GridBagLayout());

        btnEditProyek.setText("Edit");
        btnEditProyek.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditProyekActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(35, 18, 35, 0);
        jPanel17.add(btnEditProyek, gridBagConstraints);

        btnHapusProyek.setText("Hapus");
        btnHapusProyek.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusProyekActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(35, 18, 35, 184);
        jPanel17.add(btnHapusProyek, gridBagConstraints);

        btnTambahProyek.setText("Tambah");
        btnTambahProyek.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahProyekActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(35, 165, 35, 0);
        jPanel17.add(btnTambahProyek, gridBagConstraints);

        jPanel4.add(jPanel17, java.awt.BorderLayout.PAGE_END);

        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jInternalFrame6.setClosable(true);
        jInternalFrame6.setVisible(false);

        jLabel25.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel25.setText("Tambah Data Proyek");

        jLabel26.setText("Nama Proyek");

        jLabel27.setText("Durasi Pengerjaan");

        btnTP_Simpan.setText("Simpan");
        btnTP_Simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTP_SimpanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel26Layout = new javax.swing.GroupLayout(jPanel26);
        jPanel26.setLayout(jPanel26Layout);
        jPanel26Layout.setHorizontalGroup(
            jPanel26Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel26Layout.createSequentialGroup()
                .addGroup(jPanel26Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel26Layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addGroup(jPanel26Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel26)
                            .addComponent(jLabel27)
                            .addComponent(tfTP_NamaProyek, javax.swing.GroupLayout.DEFAULT_SIZE, 217, Short.MAX_VALUE)
                            .addComponent(tfTP_DurasiPengerjaan)))
                    .addGroup(jPanel26Layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(jLabel25))
                    .addGroup(jPanel26Layout.createSequentialGroup()
                        .addGap(132, 132, 132)
                        .addComponent(btnTP_Simpan)))
                .addContainerGap(68, Short.MAX_VALUE))
        );
        jPanel26Layout.setVerticalGroup(
            jPanel26Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel26Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel25)
                .addGap(18, 18, 18)
                .addComponent(jLabel26)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfTP_NamaProyek, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel27)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfTP_DurasiPengerjaan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnTP_Simpan)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jInternalFrame6Layout = new javax.swing.GroupLayout(jInternalFrame6.getContentPane());
        jInternalFrame6.getContentPane().setLayout(jInternalFrame6Layout);
        jInternalFrame6Layout.setHorizontalGroup(
            jInternalFrame6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel26, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jInternalFrame6Layout.setVerticalGroup(
            jInternalFrame6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame6Layout.createSequentialGroup()
                .addComponent(jPanel26, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel9.add(jInternalFrame6, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 30, 360, -1));

        jInternalFrame7.setClosable(true);
        jInternalFrame7.setVisible(false);

        jLabel29.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel29.setText("Edit Data Proyek");

        jLabel30.setText("ID");

        jLabel31.setText("Nama Proyek *(data baru)");

        jLabel32.setText("Durasi Pengerjaan *(data baru)");

        btnEP_Simpan.setText("Simpan");
        btnEP_Simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEP_SimpanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel27Layout = new javax.swing.GroupLayout(jPanel27);
        jPanel27.setLayout(jPanel27Layout);
        jPanel27Layout.setHorizontalGroup(
            jPanel27Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel27Layout.createSequentialGroup()
                .addGroup(jPanel27Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel27Layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addGroup(jPanel27Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel30)
                            .addComponent(jLabel31)
                            .addComponent(jLabel32)
                            .addComponent(tfEP_Id, javax.swing.GroupLayout.DEFAULT_SIZE, 217, Short.MAX_VALUE)
                            .addComponent(tfEP_NamaProyek)
                            .addComponent(tfEP_DurasiPengerjaan)))
                    .addGroup(jPanel27Layout.createSequentialGroup()
                        .addGap(132, 132, 132)
                        .addComponent(btnEP_Simpan)))
                .addContainerGap(68, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel27Layout.createSequentialGroup()
                .addGap(0, 119, Short.MAX_VALUE)
                .addComponent(jLabel29)
                .addGap(117, 117, 117))
        );
        jPanel27Layout.setVerticalGroup(
            jPanel27Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel27Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel29)
                .addGap(18, 18, 18)
                .addComponent(jLabel30)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfEP_Id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel31)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfEP_NamaProyek, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel32)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfEP_DurasiPengerjaan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnEP_Simpan)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jInternalFrame7Layout = new javax.swing.GroupLayout(jInternalFrame7.getContentPane());
        jInternalFrame7.getContentPane().setLayout(jInternalFrame7Layout);
        jInternalFrame7Layout.setHorizontalGroup(
            jInternalFrame7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel27, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jInternalFrame7Layout.setVerticalGroup(
            jInternalFrame7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel27, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel9.add(jInternalFrame7, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 0, 360, -1));

        jInternalFrame8.setClosable(true);
        jInternalFrame8.setVisible(false);

        jLabel34.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel34.setText("Hapus Data Proyek");

        jLabel35.setText("ID");

        btnHP_Hapus.setText("Hapus");
        btnHP_Hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHP_HapusActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel28Layout = new javax.swing.GroupLayout(jPanel28);
        jPanel28.setLayout(jPanel28Layout);
        jPanel28Layout.setHorizontalGroup(
            jPanel28Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel28Layout.createSequentialGroup()
                .addGroup(jPanel28Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel28Layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addGroup(jPanel28Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel35)
                            .addComponent(tfHP_Id, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel28Layout.createSequentialGroup()
                        .addGap(109, 109, 109)
                        .addComponent(jLabel34))
                    .addGroup(jPanel28Layout.createSequentialGroup()
                        .addGap(133, 133, 133)
                        .addComponent(btnHP_Hapus)))
                .addContainerGap(68, Short.MAX_VALUE))
        );
        jPanel28Layout.setVerticalGroup(
            jPanel28Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel28Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel34)
                .addGap(18, 18, 18)
                .addComponent(jLabel35)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfHP_Id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnHP_Hapus)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jInternalFrame8Layout = new javax.swing.GroupLayout(jInternalFrame8.getContentPane());
        jInternalFrame8.getContentPane().setLayout(jInternalFrame8Layout);
        jInternalFrame8Layout.setHorizontalGroup(
            jInternalFrame8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel28, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jInternalFrame8Layout.setVerticalGroup(
            jInternalFrame8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel28, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel9.add(jInternalFrame8, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 0, 360, -1));

        TbProyek.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID", "Nama Proyek", "Durasi Pengerjaan"
            }
        ));
        jScrollPane2.setViewportView(TbProyek);
        if (TbProyek.getColumnModel().getColumnCount() > 0) {
            TbProyek.getColumnModel().getColumn(0).setResizable(false);
        }

        jPanel9.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 602, 372));

        jPanel4.add(jPanel9, java.awt.BorderLayout.CENTER);

        jTabbedPane1.addTab("Proyek", jPanel4);

        jPanel5.setLayout(new java.awt.BorderLayout());

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel14.setText("Tabel Transaksi");
        jPanel20.add(jLabel14);

        jPanel5.add(jPanel20, java.awt.BorderLayout.PAGE_START);

        jPanel21.setLayout(new java.awt.GridBagLayout());

        btnEditTransaksi.setText("Edit");
        btnEditTransaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditTransaksiActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(35, 18, 35, 0);
        jPanel21.add(btnEditTransaksi, gridBagConstraints);

        btnHapusTransaksi.setText("Hapus");
        btnHapusTransaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusTransaksiActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(35, 18, 35, 184);
        jPanel21.add(btnHapusTransaksi, gridBagConstraints);

        btnTambahTransaksi.setText("Tambah");
        btnTambahTransaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahTransaksiActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(35, 165, 35, 0);
        jPanel21.add(btnTambahTransaksi, gridBagConstraints);

        jPanel5.add(jPanel21, java.awt.BorderLayout.PAGE_END);

        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jInternalFrame9.setClosable(true);
        jInternalFrame9.setVisible(false);

        jLabel47.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel47.setText("Tambah Data Transaksi");

        jLabel48.setText("Karyawan");

        jLabel49.setText("Proyek");

        jLabel50.setText("Peran");

        btnTT_Simpan.setText("Simpan");
        btnTT_Simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTT_SimpanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel32Layout = new javax.swing.GroupLayout(jPanel32);
        jPanel32.setLayout(jPanel32Layout);
        jPanel32Layout.setHorizontalGroup(
            jPanel32Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel32Layout.createSequentialGroup()
                .addGroup(jPanel32Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel32Layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(jLabel47))
                    .addGroup(jPanel32Layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addGroup(jPanel32Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel48)
                            .addComponent(jLabel49)
                            .addComponent(jLabel50)
                            .addComponent(tfTT_Peran)
                            .addComponent(cbTT_Karyawan, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cbTT_Proyek, 0, 217, Short.MAX_VALUE)))
                    .addGroup(jPanel32Layout.createSequentialGroup()
                        .addGap(133, 133, 133)
                        .addComponent(btnTT_Simpan)))
                .addContainerGap(68, Short.MAX_VALUE))
        );
        jPanel32Layout.setVerticalGroup(
            jPanel32Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel32Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel47)
                .addGap(18, 18, 18)
                .addComponent(jLabel48)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbTT_Karyawan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jLabel49)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbTT_Proyek, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jLabel50)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfTT_Peran, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnTT_Simpan)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jInternalFrame9Layout = new javax.swing.GroupLayout(jInternalFrame9.getContentPane());
        jInternalFrame9.getContentPane().setLayout(jInternalFrame9Layout);
        jInternalFrame9Layout.setHorizontalGroup(
            jInternalFrame9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel32, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jInternalFrame9Layout.setVerticalGroup(
            jInternalFrame9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame9Layout.createSequentialGroup()
                .addComponent(jPanel32, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel10.add(jInternalFrame9, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 30, 360, -1));

        jInternalFrame10.setClosable(true);
        jInternalFrame10.setVisible(false);

        jLabel51.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel51.setText("Edit Data Transaksi");

        jLabel52.setText("ID");

        jLabel53.setText("Karyawan *(data baru)");

        jLabel54.setText("Proyek *(data baru)");

        btnET_Simpan.setText("Simpan");
        btnET_Simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnET_SimpanActionPerformed(evt);
            }
        });

        jLabel58.setText("Peran *(data baru)");

        javax.swing.GroupLayout jPanel33Layout = new javax.swing.GroupLayout(jPanel33);
        jPanel33.setLayout(jPanel33Layout);
        jPanel33Layout.setHorizontalGroup(
            jPanel33Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel33Layout.createSequentialGroup()
                .addGap(0, 101, Short.MAX_VALUE)
                .addComponent(jLabel51)
                .addGap(109, 109, 109))
            .addGroup(jPanel33Layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addGroup(jPanel33Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel58)
                    .addComponent(jLabel52)
                    .addComponent(jLabel53)
                    .addComponent(jLabel54)
                    .addComponent(cbET_Karyawan, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cbET_Proyek, 0, 217, Short.MAX_VALUE)
                    .addComponent(tfET_Peran)
                    .addComponent(tfET_Id))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel33Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnET_Simpan)
                .addGap(125, 125, 125))
        );
        jPanel33Layout.setVerticalGroup(
            jPanel33Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel33Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel51)
                .addGap(18, 18, 18)
                .addComponent(jLabel52)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfET_Id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jLabel53)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbET_Karyawan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jLabel54)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbET_Proyek, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jLabel58)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfET_Peran, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnET_Simpan)
                .addContainerGap(10, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jInternalFrame10Layout = new javax.swing.GroupLayout(jInternalFrame10.getContentPane());
        jInternalFrame10.getContentPane().setLayout(jInternalFrame10Layout);
        jInternalFrame10Layout.setHorizontalGroup(
            jInternalFrame10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel33, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jInternalFrame10Layout.setVerticalGroup(
            jInternalFrame10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel33, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel10.add(jInternalFrame10, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 0, 360, -1));

        jInternalFrame11.setClosable(true);
        jInternalFrame11.setVisible(false);

        jLabel55.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel55.setText("Hapus Data Transaksi");

        jLabel56.setText("ID");

        btnHT_Hapus.setText("Hapus");
        btnHT_Hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHT_HapusActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel34Layout = new javax.swing.GroupLayout(jPanel34);
        jPanel34.setLayout(jPanel34Layout);
        jPanel34Layout.setHorizontalGroup(
            jPanel34Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel34Layout.createSequentialGroup()
                .addGap(0, 102, Short.MAX_VALUE)
                .addComponent(jLabel55)
                .addGap(91, 91, 91))
            .addGroup(jPanel34Layout.createSequentialGroup()
                .addGroup(jPanel34Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel34Layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addGroup(jPanel34Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel56)
                            .addComponent(tfHT_Id, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel34Layout.createSequentialGroup()
                        .addGap(123, 123, 123)
                        .addComponent(btnHT_Hapus)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel34Layout.setVerticalGroup(
            jPanel34Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel34Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel55)
                .addGap(18, 18, 18)
                .addComponent(jLabel56)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfHT_Id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnHT_Hapus)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jInternalFrame11Layout = new javax.swing.GroupLayout(jInternalFrame11.getContentPane());
        jInternalFrame11.getContentPane().setLayout(jInternalFrame11Layout);
        jInternalFrame11Layout.setHorizontalGroup(
            jInternalFrame11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame11Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel34, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jInternalFrame11Layout.setVerticalGroup(
            jInternalFrame11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame11Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel34, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel10.add(jInternalFrame11, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 0, 360, -1));

        TbTransaksi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "ID Karyawan", "ID Proyek", "Peran"
            }
        ));
        jScrollPane3.setViewportView(TbTransaksi);
        if (TbTransaksi.getColumnModel().getColumnCount() > 0) {
            TbTransaksi.getColumnModel().getColumn(0).setResizable(false);
        }

        jPanel10.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 602, 372));

        jPanel5.add(jPanel10, java.awt.BorderLayout.CENTER);

        jTabbedPane1.addTab("Transaksi Proyek", jPanel5);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTambahKaryawanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahKaryawanActionPerformed
        jInternalFrame1.setVisible(true);
    }//GEN-LAST:event_btnTambahKaryawanActionPerformed

    private void btnTK_SimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTK_SimpanActionPerformed
        String nama = tfTK_Nama.getText();
        String jabatan = tfTK_Jabatan.getText();
        String departemen = tfTK_Departemen.getText();
        
        if(nama.isEmpty() || jabatan.isEmpty() || departemen.isEmpty()){
            JOptionPane.showMessageDialog(null, "Data Tidak Boleh Kosong" , "Peringatan", JOptionPane.ERROR_MESSAGE);
        } else {
            Karyawan kry = new Karyawan(0, nama, jabatan, departemen);
            kry.tambahDataKaryawan();
            jInternalFrame1.setVisible(false);
            reset();
            loadDataKaryawan();
        }
    }//GEN-LAST:event_btnTK_SimpanActionPerformed

    private void btnEK_SimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEK_SimpanActionPerformed
        String nama = tfEK_Nama.getText();
        String jabatan = tfEK_Jabatan.getText();
        String departemen = tfEK_Departemen.getText();
        String id = tfEK_Id.getText();
        try {
            if(id.isEmpty() || nama.isEmpty() || jabatan.isEmpty() || departemen.isEmpty()){
                JOptionPane.showMessageDialog(null, "Data Tidak Boleh Kosong" , "Peringatan", JOptionPane.ERROR_MESSAGE);
            } else {
                int id2 = Integer.parseInt(id);
                Karyawan kry = new Karyawan(id2, nama, jabatan, departemen);
                kry.editDataKaryawan();
                jInternalFrame4.setVisible(false);
                reset();
                loadDataKaryawan();
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Masukan Data Dengan Benar" , "Peringatan", JOptionPane.ERROR_MESSAGE);
        }
        
        
    }//GEN-LAST:event_btnEK_SimpanActionPerformed

    private void btnEditKaryawanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditKaryawanActionPerformed
        jInternalFrame4.setVisible(true);
    }//GEN-LAST:event_btnEditKaryawanActionPerformed

    private void btnHK_HapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHK_HapusActionPerformed
        String id = tfHK_Id.getText();
        try {
            if(id.isEmpty()){
                JOptionPane.showMessageDialog(null, "Data Tidak Boleh Kosong" , "Peringatan", JOptionPane.ERROR_MESSAGE);
            } else {
                int id2 = Integer.parseInt(id);
                Karyawan kry = new Karyawan(id2, "", "", "");
                kry.hapusDataKaryawan();
                jInternalFrame5.setVisible(false);
                reset();
                loadDataKaryawan();
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Masukan Data Dengan Benar" , "Peringatan", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnHK_HapusActionPerformed

    private void btnHapusKaryawanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusKaryawanActionPerformed
        jInternalFrame5.setVisible(true);
    }//GEN-LAST:event_btnHapusKaryawanActionPerformed

    private void btnTP_SimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTP_SimpanActionPerformed
        String nama_proyek = tfTP_NamaProyek.getText();
        String durasi_pengerjaan = tfTP_DurasiPengerjaan.getText();
        try {
            if(nama_proyek.isEmpty() || durasi_pengerjaan.isEmpty()){
                JOptionPane.showMessageDialog(null, "Data Tidak Boleh Kosong" , "Peringatan", JOptionPane.ERROR_MESSAGE);
            } else {
                int durasi_pengerjaan2 = Integer.parseInt(durasi_pengerjaan);
                Proyek pry = new Proyek(0, nama_proyek, durasi_pengerjaan2);
                pry.tambahDataProyek();
                jInternalFrame6.setVisible(false);
                reset();
                loadDataProyek();
            } 
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Masukan Data Dengan Benar" , "Peringatan", JOptionPane.ERROR_MESSAGE);
        }
        
        
    }//GEN-LAST:event_btnTP_SimpanActionPerformed

    private void btnEP_SimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEP_SimpanActionPerformed
        String nama_proyek = tfEP_NamaProyek.getText();
        String durasi_pengerjaan = tfEP_DurasiPengerjaan.getText();
        String id = tfEP_Id.getText();
        try {
            if(id.isEmpty() || nama_proyek.isEmpty() || durasi_pengerjaan.isEmpty()){
                JOptionPane.showMessageDialog(null, "Data Tidak Boleh Kosong" , "Peringatan", JOptionPane.ERROR_MESSAGE);
            } else {
                int durasi_pengerjaan2 = Integer.parseInt(durasi_pengerjaan);
                int id2 = Integer.parseInt(id);
                Proyek pry = new Proyek(id2, nama_proyek, durasi_pengerjaan2);
                pry.editDataProyek();
                jInternalFrame7.setVisible(false);
                reset();
                loadDataProyek();
            } 
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Masukan Data Dengan Benar" , "Peringatan", JOptionPane.ERROR_MESSAGE);
        }
        
    }//GEN-LAST:event_btnEP_SimpanActionPerformed

    private void btnHP_HapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHP_HapusActionPerformed
        String id = tfHP_Id.getText();
        try {
            if(id.isEmpty()){
                JOptionPane.showMessageDialog(null, "Data Tidak Boleh Kosong" , "Peringatan", JOptionPane.ERROR_MESSAGE);
            } else {
                int id2 = Integer.parseInt(id);
                Proyek pry = new Proyek(id2, "", 0);
                pry.hapusDataProyek();
                jInternalFrame8.setVisible(false);
                reset();
                loadDataProyek();
            } 
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Masukan Data Dengan Benar" , "Peringatan", JOptionPane.ERROR_MESSAGE);
        }
        
    }//GEN-LAST:event_btnHP_HapusActionPerformed

    private void btnTambahProyekActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahProyekActionPerformed
        jInternalFrame6.setVisible(true);
    }//GEN-LAST:event_btnTambahProyekActionPerformed

    private void btnEditProyekActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditProyekActionPerformed
        jInternalFrame7.setVisible(true);
    }//GEN-LAST:event_btnEditProyekActionPerformed

    private void btnHapusProyekActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusProyekActionPerformed
        jInternalFrame8.setVisible(true);
    }//GEN-LAST:event_btnHapusProyekActionPerformed

    private void btnET_SimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnET_SimpanActionPerformed
        String data_karyawan = cbET_Karyawan.getSelectedItem().toString();
        String data_proyek = cbET_Proyek.getSelectedItem().toString();
        String peran = tfET_Peran.getText();
        String id = tfET_Id.getText();
        try {
            if(id.isEmpty() || cbET_Karyawan.getSelectedIndex() == 0 || cbET_Proyek.getSelectedIndex() == 0 || peran.isEmpty()){
                JOptionPane.showMessageDialog(null, "Data Tidak Boleh Kosong" , "Peringatan", JOptionPane.ERROR_MESSAGE);
            } else {
                int id2 = Integer.parseInt(id);
                String[] ambilIdKaryawan = data_karyawan.split("\\|");
                int id_karyawan = Integer.parseInt(ambilIdKaryawan[0].trim());
                String[] ambilIdPoyek = data_proyek.split("\\|");
                int id_proyek = Integer.parseInt(ambilIdPoyek[0].trim());
                Transaksi tsk = new Transaksi(id2, id_karyawan, id_proyek, peran);
                tsk.editDataTransaksi();
                jInternalFrame10.setVisible(false);
                resetTransaksi();
                loadDataTransaksi();
            } 
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Masukan Data Dengan Benar" , "Peringatan", JOptionPane.ERROR_MESSAGE);
        }
        
    }//GEN-LAST:event_btnET_SimpanActionPerformed

    private void btnHT_HapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHT_HapusActionPerformed
        String id = tfHT_Id.getText();
        try {
            if(id.isEmpty()){
                JOptionPane.showMessageDialog(null, "Data Tidak Boleh Kosong" , "Peringatan", JOptionPane.ERROR_MESSAGE);
            } else {
                int id2 = Integer.parseInt(id);
                Transaksi tsk = new Transaksi(id2, 0, 0, "");
                tsk.hapusDataTransaksi();
                jInternalFrame11.setVisible(false);
                resetTransaksi();
                loadDataTransaksi();
            } 
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Masukan Data Dengan Benar" , "Peringatan", JOptionPane.ERROR_MESSAGE);
        }
        
    }//GEN-LAST:event_btnHT_HapusActionPerformed

    private void btnTambahTransaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahTransaksiActionPerformed
        jInternalFrame9.setVisible(true);
        cbTT_Karyawan.addItem("ID | Nama | Jabatan | Departemen");
        String sql = "SELECT * FROM karyawan";
        try (
            PreparedStatement stmt = conn.prepareStatement(sql);
            ResultSet rs = stmt.executeQuery())
        {
            while(rs.next()){
                int id = rs.getInt("id");
                String nama = rs.getString("nama");
                String jabatan = rs.getString("jabatan");
                String departemen = rs.getString("departemen");
                cbTT_Karyawan.addItem(id + " | " + nama + " | " + jabatan + " | " + departemen);
            }
            
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "error");
        }
        
        cbTT_Proyek.addItem("ID | Nama Proyek | Durasi Pengerjaan");
        String sql2 = "SELECT * FROM proyek";
        try (
            PreparedStatement stmt2 = conn.prepareStatement(sql2);
            ResultSet rs2 = stmt2.executeQuery())
        {
            while(rs2.next()){
                int id = rs2.getInt("id");
                String nama_proyek = rs2.getString("nama_proyek");
                String durasi_pengerjaan = rs2.getString("durasi_pengerjaan");
                cbTT_Proyek.addItem(id + " | " + nama_proyek + " | " + durasi_pengerjaan);
            }
            
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "error");
        }
    }//GEN-LAST:event_btnTambahTransaksiActionPerformed

    private void btnEditTransaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditTransaksiActionPerformed
        jInternalFrame10.setVisible(true); 
        cbET_Karyawan.addItem("ID | Nama | Jabatan | Departemen");
        String sql = "SELECT * FROM karyawan";
        try (
            PreparedStatement stmt = conn.prepareStatement(sql);
            ResultSet rs = stmt.executeQuery())
        {
            while(rs.next()){
                int id = rs.getInt("id");
                String nama = rs.getString("nama");
                String jabatan = rs.getString("jabatan");
                String departemen = rs.getString("departemen");
                cbET_Karyawan.addItem(id + " | " + nama + " | " + jabatan + " | " + departemen);
            }
            
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "error");
        }
        
        cbET_Proyek.addItem("ID | Nama Proyek | Durasi Pengerjaan");
        String sql2 = "SELECT * FROM proyek";
        try (
            PreparedStatement stmt2 = conn.prepareStatement(sql2);
            ResultSet rs2 = stmt2.executeQuery())
        {
            while(rs2.next()){
                int id = rs2.getInt("id");
                String nama_proyek = rs2.getString("nama_proyek");
                String durasi_pengerjaan = rs2.getString("durasi_pengerjaan");
                cbET_Proyek.addItem(id + " | " + nama_proyek + " | " + durasi_pengerjaan);
            }
            
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "error");
        }
    }//GEN-LAST:event_btnEditTransaksiActionPerformed

    private void btnHapusTransaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusTransaksiActionPerformed
        jInternalFrame11.setVisible(true);
    }//GEN-LAST:event_btnHapusTransaksiActionPerformed

    private void btnTT_SimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTT_SimpanActionPerformed
        String data_karyawan = cbTT_Karyawan.getSelectedItem().toString();
        String data_proyek = cbTT_Proyek.getSelectedItem().toString();
        String peran = tfTT_Peran.getText();

        if(cbTT_Karyawan.getSelectedIndex() == 0 || cbTT_Proyek.getSelectedIndex() == 0 || peran.isEmpty()){
            JOptionPane.showMessageDialog(null, "Data Tidak Boleh Kosong" , "Peringatan", JOptionPane.ERROR_MESSAGE);
        } else {
            String[] ambilIdKaryawan = data_karyawan.split("\\|");
            int id_karyawan = Integer.parseInt(ambilIdKaryawan[0].trim());
            String[] ambilIdPoyek = data_proyek.split("\\|");
            int id_proyek = Integer.parseInt(ambilIdPoyek[0].trim());
            Transaksi tsk = new Transaksi(0, id_karyawan, id_proyek, peran);
            tsk.tambahDataTransaksi();
            jInternalFrame9.setVisible(false);
            resetTransaksi();
            loadDataTransaksi();
        } 

    }//GEN-LAST:event_btnTT_SimpanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new App().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TbKaryawan;
    private javax.swing.JTable TbProyek;
    private javax.swing.JTable TbTransaksi;
    private javax.swing.JButton btnEK_Simpan;
    private javax.swing.JButton btnEP_Simpan;
    private javax.swing.JButton btnET_Simpan;
    private javax.swing.JButton btnEditKaryawan;
    private javax.swing.JButton btnEditProyek;
    private javax.swing.JButton btnEditTransaksi;
    private javax.swing.JButton btnHK_Hapus;
    private javax.swing.JButton btnHP_Hapus;
    private javax.swing.JButton btnHT_Hapus;
    private javax.swing.JButton btnHapusKaryawan;
    private javax.swing.JButton btnHapusProyek;
    private javax.swing.JButton btnHapusTransaksi;
    private javax.swing.JButton btnTK_Simpan;
    private javax.swing.JButton btnTP_Simpan;
    private javax.swing.JButton btnTT_Simpan;
    private javax.swing.JButton btnTambahKaryawan;
    private javax.swing.JButton btnTambahProyek;
    private javax.swing.JButton btnTambahTransaksi;
    private javax.swing.JComboBox<String> cbET_Karyawan;
    private javax.swing.JComboBox<String> cbET_Proyek;
    private javax.swing.JComboBox<String> cbTT_Karyawan;
    private javax.swing.JComboBox<String> cbTT_Proyek;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JInternalFrame jInternalFrame10;
    private javax.swing.JInternalFrame jInternalFrame11;
    private javax.swing.JInternalFrame jInternalFrame4;
    private javax.swing.JInternalFrame jInternalFrame5;
    private javax.swing.JInternalFrame jInternalFrame6;
    private javax.swing.JInternalFrame jInternalFrame7;
    private javax.swing.JInternalFrame jInternalFrame8;
    private javax.swing.JInternalFrame jInternalFrame9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel24;
    private javax.swing.JPanel jPanel25;
    private javax.swing.JPanel jPanel26;
    private javax.swing.JPanel jPanel27;
    private javax.swing.JPanel jPanel28;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel32;
    private javax.swing.JPanel jPanel33;
    private javax.swing.JPanel jPanel34;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField tfEK_Departemen;
    private javax.swing.JTextField tfEK_Id;
    private javax.swing.JTextField tfEK_Jabatan;
    private javax.swing.JTextField tfEK_Nama;
    private javax.swing.JTextField tfEP_DurasiPengerjaan;
    private javax.swing.JTextField tfEP_Id;
    private javax.swing.JTextField tfEP_NamaProyek;
    private javax.swing.JTextField tfET_Id;
    private javax.swing.JTextField tfET_Peran;
    private javax.swing.JTextField tfHK_Id;
    private javax.swing.JTextField tfHP_Id;
    private javax.swing.JTextField tfHT_Id;
    private javax.swing.JTextField tfTK_Departemen;
    private javax.swing.JTextField tfTK_Jabatan;
    private javax.swing.JTextField tfTK_Nama;
    private javax.swing.JTextField tfTP_DurasiPengerjaan;
    private javax.swing.JTextField tfTP_NamaProyek;
    private javax.swing.JTextField tfTT_Peran;
    // End of variables declaration//GEN-END:variables
}
