/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import java.awt.event.ActionListener;
import java.sql.SQLException;
import java.util.List;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author ZENDIA AMELIA
 */
public class Modul5 extends javax.swing.JFrame {
    private DefaultTableModel model1;
    private DefaultTableModel model2;
    private DefaultTableModel model3;
    private TBKaryawan Karyawan = new TBKaryawan();
    private TBProyek Proyek = new TBProyek();
    private TBTransaksi Transaksi = new TBTransaksi();
    /**
     * Creates new form Modul5
     */
    public Modul5() {
        initComponents();
        model1 = new DefaultTableModel(new String[]{"ID", "Nama", "Jabatan", "Dapartemen"}, 0);
        model2 = new DefaultTableModel(new String[]{"ID", "Durasi", "Nama_Proyek"}, 0);
        model3 = new DefaultTableModel(new String[]{"ID Karyawan", "ID Proyek", "Peran", "Durasi"}, 0);
        loadDataKaryawan();
        loadDataProyek();
        loadDataTransaksi();
        
        TabelKaryawan.getSelectionModel().addListSelectionListener(event -> {
        int selectedRow = TabelKaryawan.getSelectedRow();
        if (selectedRow != -1) {
            InputKaryawan2.setText(model1.getValueAt(selectedRow, 0).toString());
            InputKaryawan1.setText(model1.getValueAt(selectedRow, 1).toString());
            InputKaryawan3.setText(model1.getValueAt(selectedRow, 2).toString());
            InputKaryawan4.setText(model1.getValueAt(selectedRow, 3).toString());
        }
    });
        
        TabelProyek.getSelectionModel().addListSelectionListener(event -> {
        int selectedRow = TabelProyek.getSelectedRow();
        if (selectedRow != -1) {
            InputProyek1.setText(model2.getValueAt(selectedRow, 0).toString());
            InputProyek3.setText(model2.getValueAt(selectedRow, 1).toString());
            InputProyek2.setText(model2.getValueAt(selectedRow, 2).toString());
        }
    });
        
        TabelTransaksi.getSelectionModel().addListSelectionListener(event -> {
        int selectedRow = TabelTransaksi.getSelectedRow();
            if (selectedRow != -1) {
        Object val1 = model3.getValueAt(selectedRow, 0);
        Object val2 = model3.getValueAt(selectedRow, 1);
        Object val3 = model3.getValueAt(selectedRow, 2);
        Object val4 = model3.getValueAt(selectedRow, 3);

        if (val1 != null) {
           Pilihan1.setSelectedItem(val1.toString());
        }
        if (val2 != null) {
            Pilihan2.setSelectedItem(val2.toString());
        }
        if (val3 != null) {
            InputTransaksi2.setText(val3.toString());
        }
         if (val4 != null) {
            InputTransaksi1.setText(val4.toString());
        }
}

        
//        if (selectedRow != -1) {
//            Pilihan1.setSelectedItem(model3.getValueAt(selectedRow, 0).toString());
//            Pilihan2.setSelectedItem(model3.getValueAt(selectedRow, 1).toString());
//            InputTransaksi2.setText(model3.getValueAt(selectedRow, 2).toString());
//            InputTransaksi1.setText(model3.getValueAt(selectedRow, 3).toString());
//        }
    });
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        InputKaryawan1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        InputKaryawan2 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        InputKaryawan3 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        InputKaryawan4 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        TabelKaryawan = new javax.swing.JTable();
        ButtonKaryawan1 = new javax.swing.JButton();
        ButtonKaryawan3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        ButtonKaryawan2 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        InputProyek3 = new javax.swing.JTextField();
        InputProyek1 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        InputProyek2 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        TabelProyek = new javax.swing.JTable();
        ButtonProyek2 = new javax.swing.JButton();
        ButtonProyek3 = new javax.swing.JButton();
        ButtonProyek1 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        TabelTransaksi = new javax.swing.JTable();
        Pilihan1 = new javax.swing.JComboBox<>();
        Pilihan2 = new javax.swing.JComboBox<>();
        InputTransaksi2 = new javax.swing.JTextField();
        ButtonTransaksi3 = new javax.swing.JButton();
        ButtonTransaksi1 = new javax.swing.JButton();
        ButtonTransaksi2 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        InputTransaksi1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jLabel1.setText("Aplikasi Manajemen Karyawan dan Proyek");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 6, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 328, Short.MAX_VALUE)
        );

        jPanel3.setBackground(new java.awt.Color(51, 0, 51));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Segoe UI Light", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Nama");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 20, -1, -1));
        jPanel3.add(InputKaryawan1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 40, 160, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI Light", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Id");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 70, -1, -1));
        jPanel3.add(InputKaryawan2, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 90, 160, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI Light", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Jabatan");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 120, -1, -1));
        jPanel3.add(InputKaryawan3, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 150, 160, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI Light", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Departemen");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 180, -1, -1));
        jPanel3.add(InputKaryawan4, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 200, 160, -1));

        TabelKaryawan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Id", "Nama", "Bidang Pekerjaan", "Departemen"
            }
        ));
        jScrollPane1.setViewportView(TabelKaryawan);

        jPanel3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, 210));

        ButtonKaryawan1.setText("Update");
        ButtonKaryawan1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonKaryawan1ActionPerformed(evt);
            }
        });
        jPanel3.add(ButtonKaryawan1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, -1, -1));

        ButtonKaryawan3.setText("Tambah");
        ButtonKaryawan3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonKaryawan3ActionPerformed(evt);
            }
        });
        jPanel3.add(ButtonKaryawan3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 240, -1, -1));

        jButton2.setText("Hapus");
        jPanel3.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(9, 479, -1, -1));

        ButtonKaryawan2.setText("Hapus");
        ButtonKaryawan2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonKaryawan2ActionPerformed(evt);
            }
        });
        jPanel3.add(ButtonKaryawan2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 240, -1, -1));

        jTabbedPane1.addTab("Karyawan", jPanel3);

        jPanel4.setBackground(new java.awt.Color(204, 204, 255));
        jPanel4.setLayout(null);

        jLabel6.setFont(new java.awt.Font("Segoe UI Light", 1, 12)); // NOI18N
        jLabel6.setText("Durasi");
        jPanel4.add(jLabel6);
        jLabel6.setBounds(10, 110, 70, 16);
        jPanel4.add(InputProyek3);
        InputProyek3.setBounds(10, 130, 170, 22);
        jPanel4.add(InputProyek1);
        InputProyek1.setBounds(10, 30, 170, 22);

        jLabel7.setFont(new java.awt.Font("Segoe UI Light", 1, 12)); // NOI18N
        jLabel7.setText("Id Proyek");
        jPanel4.add(jLabel7);
        jLabel7.setBounds(10, 10, 70, 16);
        jPanel4.add(InputProyek2);
        InputProyek2.setBounds(10, 80, 170, 22);

        jLabel8.setFont(new java.awt.Font("Segoe UI Light", 1, 12)); // NOI18N
        jLabel8.setText("Nama Proyek");
        jPanel4.add(jLabel8);
        jLabel8.setBounds(10, 60, 100, 16);

        TabelProyek.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Id Proyek", "Nama Proyek", "Durasi"
            }
        ));
        jScrollPane2.setViewportView(TabelProyek);

        jPanel4.add(jScrollPane2);
        jScrollPane2.setBounds(192, 10, 470, 250);

        ButtonProyek2.setText("Tambah");
        ButtonProyek2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonProyek2ActionPerformed(evt);
            }
        });
        jPanel4.add(ButtonProyek2);
        ButtonProyek2.setBounds(10, 210, 160, 30);

        ButtonProyek3.setText("Hapus");
        ButtonProyek3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonProyek3ActionPerformed(evt);
            }
        });
        jPanel4.add(ButtonProyek3);
        ButtonProyek3.setBounds(10, 250, 160, 30);

        ButtonProyek1.setText("Update");
        ButtonProyek1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonProyek1ActionPerformed(evt);
            }
        });
        jPanel4.add(ButtonProyek1);
        ButtonProyek1.setBounds(10, 170, 160, 30);

        jTabbedPane1.addTab("Proyek", jPanel4);

        jPanel5.setBackground(new java.awt.Color(102, 0, 0));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Segoe UI Light", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Peran");
        jPanel5.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 200, -1, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI Light", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText(" Id Karyawan");
        jPanel5.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 30, -1, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI Light", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Id Proyek");
        jPanel5.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 90, -1, 10));

        TabelTransaksi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "id karyawan", " id Proyek", "Peran", "DurasI Mingguan"
            }
        ));
        jScrollPane3.setViewportView(TabelTransaksi);

        jPanel5.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 470, 190));

        Pilihan1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Karyawan" }));
        Pilihan1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Pilihan1ActionPerformed(evt);
            }
        });
        jPanel5.add(Pilihan1, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 50, 150, -1));

        Pilihan2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Proyek" }));
        jPanel5.add(Pilihan2, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 110, 150, -1));
        jPanel5.add(InputTransaksi2, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 220, 150, -1));

        ButtonTransaksi3.setText("Hapus");
        ButtonTransaksi3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonTransaksi3ActionPerformed(evt);
            }
        });
        jPanel5.add(ButtonTransaksi3, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 230, 150, 30));

        ButtonTransaksi1.setText("Tambah");
        ButtonTransaksi1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonTransaksi1ActionPerformed(evt);
            }
        });
        jPanel5.add(ButtonTransaksi1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 140, 30));

        ButtonTransaksi2.setText("Update");
        ButtonTransaksi2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonTransaksi2ActionPerformed(evt);
            }
        });
        jPanel5.add(ButtonTransaksi2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 230, 140, 30));

        jLabel12.setFont(new java.awt.Font("Segoe UI Light", 1, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Durasi");
        jPanel5.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 150, -1, -1));
        jPanel5.add(InputTransaksi1, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 170, 150, -1));

        jTabbedPane1.addTab("Transaksi", jPanel5);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 685, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(200, 200, 200)
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonKaryawan3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonKaryawan3ActionPerformed
        // TODO add your handling code here:
        String val_id = InputKaryawan2.getText();
        String val_nama = InputKaryawan1.getText();
        String val_jabatan = InputKaryawan3.getText();
        String val_dapartemen = InputKaryawan4.getText();
        
        BagianKaryawan brg = new BagianKaryawan(
        0,
        val_nama,
        val_jabatan,
        val_dapartemen
        );
        
         try {
            Karyawan.InsertKaryawan(brg);
            loadDataKaryawan(); 
            System.out.println("Data berhasil disimpan");
        } catch (SQLException e) {
            System.out.println("Tidak dapat Menambahhkan barang, error" + e);
        }
    }//GEN-LAST:event_ButtonKaryawan3ActionPerformed

    private void ButtonProyek2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonProyek2ActionPerformed
        // TODO add your handling code here:
        String val_id = InputProyek1.getText();
        String val_durasi = InputProyek3.getText();
        String val_nama_proyek = InputProyek2.getText();
        
        int durasi = 0;
        
        try {
            // Konversi val_durasi ke int jika tidak kosong
            if (!val_durasi.isEmpty()) {
                durasi = Integer.parseInt(val_durasi);
            } else {
                System.out.println("Durasi tidak boleh kosong.");
                return;
            }
        } catch (NumberFormatException e) {
            System.out.println("Durasi harus berupa angka valid: " + e.getMessage());
            return;
        }
        
        BagianProyek barang = new BagianProyek(
            0,             // ID akan di-generate oleh database
            durasi,        // Nilai durasi yang dikonversi
            val_nama_proyek
        );

        try {
            Proyek.InsertProyek(barang);
            loadDataProyek();
            System.out.println("Data berhasil disimpan");
        } catch (SQLException e) {
            System.out.println("Tidak dapat menambahkan proyek, error: " + e);
        }
    }//GEN-LAST:event_ButtonProyek2ActionPerformed

    private void ButtonProyek3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonProyek3ActionPerformed
        // TODO add your handling code here:
         int selectedRow = TabelProyek.getSelectedRow();
        if (selectedRow == -1) {
            System.out.println("Pilih baris yang akan dihapus");
            return;
        }

        int id = (int) model2.getValueAt(selectedRow, 0);

        try {
            Proyek.deleteProyek(id);
            loadDataProyek();
            System.out.println("Data berhasil dihapus");
        } catch (SQLException e) {
            System.out.println("Tidak dapat menghapus data, error: " + e.getMessage());
            }
    }//GEN-LAST:event_ButtonProyek3ActionPerformed

    private void ButtonProyek1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonProyek1ActionPerformed
        // TODO add your handling code here:
        int selectedRow = TabelProyek.getSelectedRow();
        if (selectedRow == -1) {
            System.out.println("Pilih baris yang akan diubah");
            return;
        }

        // Mendapatkan nilai ID dari tabel dan memeriksa apakah nilainya tidak kosong
        Object idValue = model2.getValueAt(selectedRow, 0);

        if (idValue == null || idValue.toString().isEmpty()) {
            System.out.println("ID tidak valid atau kosong.");
            return;
        }

        try {
            int id = Integer.parseInt(idValue.toString());

            // Mendapatkan nilai dari JTextField untuk durasi dan nama proyek
            int durasi = Integer.parseInt(InputProyek3.getText());  // Pastikan Durasi diambil dari JTextField
            String nama_proyek = InputProyek2.getText();

            // Membuat objek BarangProyek dengan data yang diperbarui
            BagianProyek barang = new BagianProyek(id, durasi, nama_proyek);

            // Mengupdate data proyek di database
            try {
                Proyek.updateProyek(barang);
                loadDataProyek();
                System.out.println("Data berhasil diubah");
            } catch (SQLException e) {
                System.out.println("Tidak dapat mengubah data, error: " + e.getMessage());
            }
        } catch (NumberFormatException e) {
            System.out.println("ID atau Durasi tidak valid: " + e.getMessage());
        }
    }//GEN-LAST:event_ButtonProyek1ActionPerformed

    private void ButtonKaryawan2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonKaryawan2ActionPerformed
        // TODO add your handling code here:
        int selectedRow = TabelKaryawan.getSelectedRow();
        if (selectedRow == -1) {
            System.out.println("Pilih baris yang akan dihapus");
            return;
        }

        int id = (int) model1.getValueAt(selectedRow, 0);

        try {
            Karyawan.deleteKaryawan(id);
            loadDataKaryawan();
            System.out.println("Data berhasil dihapus");
        } catch (SQLException e) {
            System.out.println("Tidak dapat menghapus data, error: " + e.getMessage());
            }
    }//GEN-LAST:event_ButtonKaryawan2ActionPerformed

    private void ButtonKaryawan1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonKaryawan1ActionPerformed
        // TODO add your handling code here:
        int selectedRow = TabelKaryawan.getSelectedRow();
        if (selectedRow == -1) {
            System.out.println("Pilih baris yang akan diubah");
            return;
        }

        // Mendapatkan nilai ID dari tabel dan memeriksa apakah nilainya tidak kosong
        Object idValue = model1.getValueAt(selectedRow, 0);
        if (idValue == null || idValue.toString().isEmpty()) {
            System.out.println("ID tidak valid atau kosong.");
            return;
        }

        try {
            int id = Integer.parseInt(idValue.toString());
            String nama = InputKaryawan1.getText();
            String jabatan = InputKaryawan3.getText();
            String dapartemen = InputKaryawan4.getText();
            
            // Membuat objek Barang dengan data yang diperbarui
            BagianKaryawan barang = new BagianKaryawan(id, nama, jabatan, dapartemen);

            // Mengupdate data barang
            try {
                Karyawan.updateKaryawan(barang);
                loadDataKaryawan(); 
                System.out.println("Data berhasil diubah");
            } catch (SQLException e) {
                System.out.println("Tidak dapat mengubah data, error: " + e.getMessage());
            }
        } catch (NumberFormatException e) {
            System.out.println("ID tidak valid: " + e.getMessage());
        }
    }//GEN-LAST:event_ButtonKaryawan1ActionPerformed

    private void ButtonTransaksi2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonTransaksi2ActionPerformed
        // TODO add your handling code here:
         int selectedRow = TabelTransaksi.getSelectedRow();
        if (selectedRow == -1) {
            System.out.println("Pilih baris yang akan diubah");
            return;
        }

        Object idValue = model3.getValueAt(selectedRow, 0);

        if (idValue == null || idValue.toString().isEmpty()) {
            System.out.println("ID tidak valid atau kosong.");
            return;
        }

        try {
            int kategori1 = Integer.parseInt(Pilihan1.getSelectedItem().toString().split(" - ")[0]);
            int kategori2 = Integer.parseInt(Pilihan2.getSelectedItem().toString().split(" - ")[0]);
//            String kategori = PilihanKategori.getSelectedItem().toString();
            String peran = InputTransaksi2.getText();
            int durasi = Integer.parseInt(InputTransaksi1.getText());

            // Membuat objek BarangProyek dengan data yang diperbarui
            BagianTransaksi barang = new BagianTransaksi(kategori1, kategori2, peran, durasi);

            // Mengupdate data proyek di database
            try {
                Transaksi.updateTransaksi(barang);
                loadDataTransaksi();
                System.out.println("Data berhasil diubah");
            } catch (SQLException e) {
                System.out.println("Tidak dapat mengubah data, error: " + e.getMessage());
            }
        } catch (NumberFormatException e) {
            System.out.println("ID atau Durasi tidak valid: " + e.getMessage());
        }
    }//GEN-LAST:event_ButtonTransaksi2ActionPerformed

    private void ButtonTransaksi1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonTransaksi1ActionPerformed
        // TODO add your handling code here:
        String val_idkaryawan = Pilihan1.getSelectedItem().toString().split(" - ")[0];
        String val_idproyek = Pilihan2.getSelectedItem().toString().split(" - ")[0];
        String val_peran = InputTransaksi2.getText();
        int val_durasi = Integer.parseInt(InputTransaksi1.getText());
        

        // Pastikan ID karyawan dan ID proyek dikonversi ke tipe integer jika dibutuhkan
        int idKaryawan = Integer.parseInt(val_idkaryawan);
        int idProyek = Integer.parseInt(val_idproyek);

        // Buat objek BarangTransaksi
        BagianTransaksi brg = new BagianTransaksi(
            idKaryawan,
            idProyek,
            val_peran,
            val_durasi
        );

        try {
            Transaksi.InsertTransaksi(brg);
            loadDataTransaksi(); 
            System.out.println("Data berhasil disimpan");
        } catch (SQLException e) {
            System.out.println("Tidak dapat Menambahkan Data, error: " + e);
        }
    }//GEN-LAST:event_ButtonTransaksi1ActionPerformed

    private void ButtonTransaksi3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonTransaksi3ActionPerformed
        // TODO add your handling code here:
         int selectedRow = TabelTransaksi.getSelectedRow();
        if (selectedRow == -1) {
            System.out.println("Pilih baris yang akan dihapus");
            return;
        }

        int id = (int) model3.getValueAt(selectedRow, 0);

        try {
            Transaksi.deleteTransaksi(id);
            loadDataTransaksi();
            System.out.println("Data berhasil dihapus");
        } catch (SQLException e) {
            System.out.println("Tidak dapat menghapus data, error: " + e.getMessage());
            }
    }//GEN-LAST:event_ButtonTransaksi3ActionPerformed

    private void Pilihan1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Pilihan1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Pilihan1ActionPerformed

    /**
     * @param args the command line arguments
     */
    
    public void loadDataKaryawan() {
        model1.setRowCount(0);
        Pilihan1.removeAllItems();
        Pilihan1.addItem("-- Karyawan--");
        try {
            List<BagianKaryawan> list_karyawan = Karyawan.getAllKaryawan();
            
            for (BagianKaryawan brg: list_karyawan) {
                model1.addRow(
                    new Object[]{
                       brg.getId(),
                       brg.getNama(),
                       brg.getJabatan(),
                       brg.getDapartemen()
                    }
            );
                
            // Tambah data ke ComboBox (ID Karyawan)
            Pilihan1.addItem(brg.getId() + " - " + brg.getNama());
        }
            
        TabelKaryawan.setModel(model1);
        
        } catch (SQLException e) {
            System.out.println("tidak dapat memuat data, error" + e);
        }
    }
    
    public void loadDataProyek() {
        model2.setRowCount(0);
        Pilihan2.removeAllItems();
        Pilihan2.addItem("-- Proyek --");

        try {
            List<BagianProyek> list_proyek = Proyek.getAllProyek();
            
            for (BagianProyek brg: list_proyek) {
                model2.addRow(
                    new Object[]{
                       brg.getId(),
                       brg.getDurasi(),
                       brg.getNamaProyek()
                    }
            );
            
            Pilihan2.addItem(brg.getId() + " - " + brg.getNamaProyek());
        }
            
        TabelProyek.setModel(model2);
        
        for (ActionListener al : Pilihan2.getActionListeners()) {
            Pilihan2.removeActionListener(al);
        }
        
        Pilihan2.addActionListener(e -> {
            // Ambil ID proyek dari item yang dipilih
            String selectedItem = (String) Pilihan2.getSelectedItem();
            if (selectedItem != null) {
                String idProyek = selectedItem.split(" - ")[0]; // Mendapatkan ID proyek

                // Cari durasi proyek yang sesuai
                for (BagianProyek brg : list_proyek) {
                    if (String.valueOf(brg.getId()).equals(idProyek)) {
                        InputTransaksi1.setText(String.valueOf(brg.getDurasi()));
                        break;
                    }
                }
            }
        });
        } catch (SQLException e) {
            System.out.println("tidak dapat memuat data, error" + e);
        }
    }
    
    public void loadDataTransaksi() {
        model3.setRowCount(0);
        try {
            List<BagianTransaksi> list_transaksi = Transaksi.getAllTransaksi();
            
            for (BagianTransaksi brg: list_transaksi) {
                model3.addRow(
                    new Object[]{
                       brg.getIdKaryawan(),
                       brg.getIdProyek(),
                       brg.getPeran(),
                       brg.getDurasi()
                    }
            );
        }
            
        TabelTransaksi.setModel(model3);
        
        } catch (SQLException e) {
            System.out.println("tidak dapat memuat data, error" + e);
        }
    }
    
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Modul5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Modul5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Modul5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Modul5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Modul5().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonKaryawan1;
    private javax.swing.JButton ButtonKaryawan2;
    private javax.swing.JButton ButtonKaryawan3;
    private javax.swing.JButton ButtonProyek1;
    private javax.swing.JButton ButtonProyek2;
    private javax.swing.JButton ButtonProyek3;
    private javax.swing.JButton ButtonTransaksi1;
    private javax.swing.JButton ButtonTransaksi2;
    private javax.swing.JButton ButtonTransaksi3;
    private javax.swing.JTextField InputKaryawan1;
    private javax.swing.JTextField InputKaryawan2;
    private javax.swing.JTextField InputKaryawan3;
    private javax.swing.JTextField InputKaryawan4;
    private javax.swing.JTextField InputProyek1;
    private javax.swing.JTextField InputProyek2;
    private javax.swing.JTextField InputProyek3;
    private javax.swing.JTextField InputTransaksi1;
    private javax.swing.JTextField InputTransaksi2;
    private javax.swing.JComboBox<String> Pilihan1;
    private javax.swing.JComboBox<String> Pilihan2;
    private javax.swing.JTable TabelKaryawan;
    private javax.swing.JTable TabelProyek;
    private javax.swing.JTable TabelTransaksi;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
