
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author DIKNAS
 */
public class APOTIK extends javax.swing.JFrame {

    /**
     * Creates new form APOTIK
     */
    public APOTIK() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        Bodrex = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jRadioButton2 = new javax.swing.JRadioButton();
        Combantrin = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jRadioButton3 = new javax.swing.JRadioButton();
        Entrostop = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jRadioButton4 = new javax.swing.JRadioButton();
        Komix = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jRadioButton5 = new javax.swing.JRadioButton();
        MediChoice = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jRadioButton6 = new javax.swing.JRadioButton();
        Mixagrip = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jRadioButton7 = new javax.swing.JRadioButton();
        Mylanta = new javax.swing.JButton();
        jPanel10 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jRadioButton8 = new javax.swing.JRadioButton();
        OBH = new javax.swing.JButton();
        jPanel11 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jRadioButton9 = new javax.swing.JRadioButton();
        Paracetamol = new javax.swing.JButton();
        jPanel12 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jRadioButton10 = new javax.swing.JRadioButton();
        Paramex = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setBackground(new java.awt.Color(0, 204, 255));
        jLabel1.setFont(new java.awt.Font("STLiti", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 204, 255));
        jLabel1.setText("APOTIK SEDERHANA");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(327, 327, 327)
                .addComponent(jLabel1)
                .addContainerGap(327, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabel1)
                .addContainerGap(42, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setText("KELUAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, java.awt.BorderLayout.PAGE_END);

        jPanel2.setBackground(new java.awt.Color(0, 204, 255));
        jPanel2.setMaximumSize(new java.awt.Dimension(1000, 500));
        jPanel2.setMinimumSize(new java.awt.Dimension(1000, 500));
        jPanel2.setPreferredSize(new java.awt.Dimension(900, 500));
        jPanel2.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 40, 40));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new java.awt.GridBagLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bodrexNew.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 16, 0, 16);
        jPanel3.add(jLabel2, gridBagConstraints);

        jLabel3.setText("Bodrex");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 51, 0, 0);
        jPanel3.add(jLabel3, gridBagConstraints);

        jRadioButton1.setText("Pilih");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 44, 0, 0);
        jPanel3.add(jRadioButton1, gridBagConstraints);

        Bodrex.setBackground(new java.awt.Color(0, 204, 255));
        Bodrex.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Bodrex.setText("Detail");
        Bodrex.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BodrexActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 35, 6, 0);
        jPanel3.add(Bodrex, gridBagConstraints);

        jPanel2.add(jPanel3);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(new java.awt.GridBagLayout());

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/combantrinNew.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(1, 16, 13, 16);
        jPanel4.add(jLabel4, gridBagConstraints);

        jLabel5.setText("Combantrin");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 40, 0, 0);
        jPanel4.add(jLabel5, gridBagConstraints);

        jRadioButton2.setText("Pilih");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.SOUTH;
        gridBagConstraints.insets = new java.awt.Insets(6, 21, 4, 0);
        jPanel4.add(jRadioButton2, gridBagConstraints);

        Combantrin.setBackground(new java.awt.Color(0, 204, 255));
        Combantrin.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Combantrin.setText("Detail");
        Combantrin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CombantrinActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 35, 6, 1);
        jPanel4.add(Combantrin, gridBagConstraints);

        jPanel2.add(jPanel4);

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setLayout(new java.awt.GridBagLayout());

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/entrostopNew.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 16, 0, 16);
        jPanel5.add(jLabel6, gridBagConstraints);

        jLabel7.setText("Entrostrop");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 51, 0, 0);
        jPanel5.add(jLabel7, gridBagConstraints);

        jRadioButton3.setText("Pilih");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 44, 0, 0);
        jPanel5.add(jRadioButton3, gridBagConstraints);

        Entrostop.setBackground(new java.awt.Color(0, 204, 255));
        Entrostop.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Entrostop.setText("Detail");
        Entrostop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EntrostopActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 35, 6, 0);
        jPanel5.add(Entrostop, gridBagConstraints);

        jPanel2.add(jPanel5);

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setLayout(new java.awt.GridBagLayout());

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/KomixHerbalNew.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(40, 16, 0, 16);
        jPanel7.add(jLabel8, gridBagConstraints);

        jLabel9.setText("Komix");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 51, 0, 0);
        jPanel7.add(jLabel9, gridBagConstraints);

        jRadioButton4.setText("Pilih");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 44, 0, 0);
        jPanel7.add(jRadioButton4, gridBagConstraints);

        Komix.setBackground(new java.awt.Color(0, 204, 255));
        Komix.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Komix.setText("Detail");
        Komix.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KomixActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 35, 6, 0);
        jPanel7.add(Komix, gridBagConstraints);

        jPanel2.add(jPanel7);

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));
        jPanel8.setLayout(new java.awt.GridBagLayout());

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MediChoiceNew.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(40, 16, 0, 16);
        jPanel8.add(jLabel10, gridBagConstraints);

        jLabel11.setText("MediChoice");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 40, 0, 0);
        jPanel8.add(jLabel11, gridBagConstraints);

        jRadioButton5.setText("Pilih");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 44, 0, 0);
        jPanel8.add(jRadioButton5, gridBagConstraints);

        MediChoice.setBackground(new java.awt.Color(0, 204, 255));
        MediChoice.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        MediChoice.setText("Detail");
        MediChoice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MediChoiceActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 35, 6, 0);
        jPanel8.add(MediChoice, gridBagConstraints);

        jPanel2.add(jPanel8);

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setLayout(new java.awt.GridBagLayout());

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mixagripNew.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 16, 0, 16);
        jPanel6.add(jLabel12, gridBagConstraints);

        jLabel13.setText("Mixagrip");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 51, 0, 0);
        jPanel6.add(jLabel13, gridBagConstraints);

        jRadioButton6.setText("Pilih");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 44, 0, 0);
        jPanel6.add(jRadioButton6, gridBagConstraints);

        Mixagrip.setBackground(new java.awt.Color(0, 204, 255));
        Mixagrip.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Mixagrip.setText("Detail");
        Mixagrip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MixagripActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 35, 6, 0);
        jPanel6.add(Mixagrip, gridBagConstraints);

        jPanel2.add(jPanel6);

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));
        jPanel9.setLayout(new java.awt.GridBagLayout());

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mylantaNew.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(27, 16, 0, 16);
        jPanel9.add(jLabel14, gridBagConstraints);

        jLabel15.setText("Mylanta");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 51, 0, 0);
        jPanel9.add(jLabel15, gridBagConstraints);

        jRadioButton7.setText("Pilih");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 44, 0, 0);
        jPanel9.add(jRadioButton7, gridBagConstraints);

        Mylanta.setBackground(new java.awt.Color(0, 204, 255));
        Mylanta.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Mylanta.setText("Detail");
        Mylanta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MylantaActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 35, 6, 0);
        jPanel9.add(Mylanta, gridBagConstraints);

        jPanel2.add(jPanel9);

        jPanel10.setBackground(new java.awt.Color(255, 255, 255));
        jPanel10.setLayout(new java.awt.GridBagLayout());

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/OBHNew.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 16, 0, 16);
        jPanel10.add(jLabel16, gridBagConstraints);

        jLabel17.setText("OBH");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 51, 0, 0);
        jPanel10.add(jLabel17, gridBagConstraints);

        jRadioButton8.setText("Pilih");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 44, 0, 0);
        jPanel10.add(jRadioButton8, gridBagConstraints);

        OBH.setBackground(new java.awt.Color(0, 204, 255));
        OBH.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        OBH.setText("Detail");
        OBH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OBHActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 35, 6, 0);
        jPanel10.add(OBH, gridBagConstraints);

        jPanel2.add(jPanel10);

        jPanel11.setBackground(new java.awt.Color(255, 255, 255));
        jPanel11.setLayout(new java.awt.GridBagLayout());

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/paracetamolNew.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(9, 16, 0, 16);
        jPanel11.add(jLabel18, gridBagConstraints);

        jLabel19.setText("Paracetamol");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 40, 0, 0);
        jPanel11.add(jLabel19, gridBagConstraints);

        jRadioButton9.setText("Pilih");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 44, 0, 0);
        jPanel11.add(jRadioButton9, gridBagConstraints);

        Paracetamol.setBackground(new java.awt.Color(0, 204, 255));
        Paracetamol.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Paracetamol.setText("Detail");
        Paracetamol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ParacetamolActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 35, 6, 0);
        jPanel11.add(Paracetamol, gridBagConstraints);

        jPanel2.add(jPanel11);

        jPanel12.setBackground(new java.awt.Color(255, 255, 255));
        jPanel12.setLayout(new java.awt.GridBagLayout());

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/paramexNew.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 16, 0, 16);
        jPanel12.add(jLabel20, gridBagConstraints);

        jLabel21.setText("Paramex");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 51, 0, 0);
        jPanel12.add(jLabel21, gridBagConstraints);

        jRadioButton10.setText("Pilih");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 44, 0, 0);
        jPanel12.add(jRadioButton10, gridBagConstraints);

        Paramex.setBackground(new java.awt.Color(0, 204, 255));
        Paramex.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Paramex.setText("Detail");
        Paramex.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ParamexActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 35, 6, 0);
        jPanel12.add(Paramex, gridBagConstraints);

        jPanel2.add(jPanel12);

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BodrexActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BodrexActionPerformed
      String deskripsi = 
            "Nama Obat :\n"
            + "Bodrex FLU & BATUK\n"
            + "Dosis :\n"
            + " - Dewasa : 1 kaplet 3x sehari\n"
            + " - Anak Anak : -\n"
            + "\n"
            + "Indikasi umum :"
            + "meredakan gejala flu"
            + "meredakan gejala batuk"
            + "meredakan gejala sakit kepala"
            + "meredakan gejala demam" 
        ;
        detail d = new detail();
        d.ubah("bodrexDetail.png", deskripsi);
        d.setVisible(true);         
    }//GEN-LAST:event_BodrexActionPerformed

    private void CombantrinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CombantrinActionPerformed
         String deskripsi = 
            "Nama Obat :\n"
            + "Combantrin\n"
            + "Dosis :\n"
            + " - anak 2-6 tahun : 5-10 ml\n"
            + " - anak 6-12 tahun : 10-15 ml\n"
            + " - anak > 12 tahun : 20 ml\n"
            + "\n"
            + "Indikasi umum :"
            + "Digunakan untuk mengobati infeksi cacing kremi, cacing galang, cacing tambang"
        ;
        detail d = new detail();
        d.ubah("combantrinDetail.png", deskripsi);
        d.setVisible(true);
    }//GEN-LAST:event_CombantrinActionPerformed

    private void EntrostopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EntrostopActionPerformed
        String deskripsi = 
            "Nama Obat :\n"
            + "Entrostop\n"
            + "Dosis :\n"
            + " - anak 6-12 tahun : 1x setelah setiap diare\n"
            + " - anak > 12 tahun : 2x setelah setiap diare\n"
            + "\n"
            + "Indikasi umum :"
            + "untuk mengatasi diare yang tidak diketahui penyebabnya dengan jelas"
        ;
        detail d = new detail();
        d.ubah("entrostopDetail.png", deskripsi);
        d.setVisible(true);
    }//GEN-LAST:event_EntrostopActionPerformed

    private void KomixActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KomixActionPerformed
        String deskripsi = 
            "Nama Obat :\n"
            + "Komix\n"
            + "Dosis :\n"
            + " - Dewasa > 12 tahun : 1 sachet 3x sehari\n"
            + "\n"
            + "Indikasi umum :"
            + "Meredakan batuk yang disertai gejala flu, demam, bersin dan hidung tersumbat"
        ;
        detail d = new detail();
        d.ubah("KomixHerbalDetail.png", deskripsi);
        d.setVisible(true);
    }//GEN-LAST:event_KomixActionPerformed

    private void MediChoiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MediChoiceActionPerformed
         String deskripsi = 
            "Nama Obat :\n"
            + "Medi Choice\n"
            + "Dosis :\n"
            + " - anak 6-12 tahun : 2x sehari\n"
            + " - anak > 12 tahun : 3x sehari\n"
            + "\n"
            + "Indikasi umum :"
            + "meredakan nyeri ringan hingga seperti sakit kepala, sakit gigi, nyeri otot, serta menurunkan demam"
        ;
        detail d = new detail();
        d.ubah("MediChoiceDetail.png", deskripsi);
        d.setVisible(true);
    }//GEN-LAST:event_MediChoiceActionPerformed

    private void MixagripActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MixagripActionPerformed
        String deskripsi = 
            "Nama Obat :\n"
            + "Mixagrip\n"
            + "Dosis :\n"
            + " - anak 6-12 tahun : 2x sehari\n"
            + " - anak > 12 tahun : 3x sehari\n"
            + "\n"
            + "Indikasi umum :"
            + "meredakan gejala flu yang disertai batuk"
        ;
        detail d = new detail();
        d.ubah("mixagripDetail.png", deskripsi);
        d.setVisible(true);
    }//GEN-LAST:event_MixagripActionPerformed

    private void MylantaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MylantaActionPerformed
        String deskripsi = 
            "Nama Obat :\n"
            + "Mylanta\n"
            + "Dosis :\n"
            + " - anak 6-12 tahun : 1-2x sendok 3-4x sehari\n"
            + " - anak > 12 tahun : 1/2-1x sendok 3-4x sehari\n"
            + "\n"
            + "Indikasi umum :"
            + "meredakan gejala mual"
            + "meredakan gejala nyeri lambung"
            + "meredakan gejala gejal yang berhubungan dengan asam lambung"
        ;
        detail d = new detail();
        d.ubah("mylantaDetail.png", deskripsi);
        d.setVisible(true);
    }//GEN-LAST:event_MylantaActionPerformed

    private void OBHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OBHActionPerformed
        String deskripsi = 
            "Nama Obat :\n"
            + "OBH Combi\n"
            + "Dosis :\n"
            + " - Dewasa > 12 tahun : 1 sachet 3x sehari\n"
            + "\n"
            + "Indikasi umum :"
            + "Meredakan batuk yang disertai gejala flu, demam, bersin dan hidung tersumbat"
        ;
        detail d = new detail();
        d.ubah("OBHDetail.png", deskripsi);
        d.setVisible(true);
    }//GEN-LAST:event_OBHActionPerformed

    private void ParacetamolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ParacetamolActionPerformed
        String deskripsi = 
            "Nama Obat :\n"
            + "Paracetamol\n"
            + "Dosis :\n"
            + " - anak 6-12 tahun : 2x sehari\n"
            + " - anak > 12 tahun : 3x sehari\n"
            + "\n"
            + "Indikasi umum :"
            + "meredakan nyeri ringan hingga seperti sakit kepala, sakit gigi, nyeri otot, serta menurunkan demam"
        ;
        detail d = new detail();
        d.ubah("paracetamolDetail.png", deskripsi);
        d.setVisible(true);
    }//GEN-LAST:event_ParacetamolActionPerformed

    private void ParamexActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ParamexActionPerformed
        String deskripsi = 
            "Nama Obat :\n"
            + "Paramex\n"
            + "Dosis :\n"
            + " - Dewasa : 1 kaplet 2-3x sehari\n"
            + " - Anak Anak : -\n"
            + "\n"
            + "Indikasi umum :"
            + "meredakan gejala flu"
            + "meredakan gejala sakit kepala"
            + "meredakan gejala demam" 
        ;
        detail d = new detail();
        d.ubah("paramexDetail.png", deskripsi);
        d.setVisible(true);
    }//GEN-LAST:event_ParamexActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed
                        
                                    
                                       
                   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(APOTIK.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(APOTIK.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(APOTIK.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(APOTIK.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new APOTIK().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Bodrex;
    private javax.swing.JButton Combantrin;
    private javax.swing.JButton Entrostop;
    private javax.swing.JButton Komix;
    private javax.swing.JButton MediChoice;
    private javax.swing.JButton Mixagrip;
    private javax.swing.JButton Mylanta;
    private javax.swing.JButton OBH;
    private javax.swing.JButton Paracetamol;
    private javax.swing.JButton Paramex;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton10;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JRadioButton jRadioButton5;
    private javax.swing.JRadioButton jRadioButton6;
    private javax.swing.JRadioButton jRadioButton7;
    private javax.swing.JRadioButton jRadioButton8;
    private javax.swing.JRadioButton jRadioButton9;
    // End of variables declaration//GEN-END:variables
}
