/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pemvismodul3;
import javax.swing.JOptionPane;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import javax.swing.JTextField;
import javax.swing.ButtonGroup;
import javax.swing.Icon;
/**
 *
 * @author Lavilia
 */
//kelas utama dalam Java Swing yang digunakan untuk membuat jendela aplikasi.
public class ApotekMini extends javax.swing.JFrame {

    /**
     * Creates new form ApotekMini
     */
    // konstruktor dari kelas ApotekMini
    public ApotekMini() {
        initComponents();
        tfjumlah.setEditable(false); //mencegah pengguna mengubah nilainya secara manual.
        tftotal.setEditable(false);
        tfkembali.setEditable(false);
        
        tfcash.addKeyListener(new KeyAdapter() { //untuk memasukkan jumlah uang tunai yang dibayarkan
            public void keyReleased(KeyEvent e) { //PARAMETER,memanggil secara otomatis ketika tombol diklik
                penghitungan();
              //aat pengguna melepas sebuah tombol pada keyboard, program akan memicu metode penghitungan
            }
        });
          tfjumlah.setText("0"); //menampilkan jumlah item yang dipilih pengguna
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private void penghitungan() {
        try { // menangkap kemungkinan error yang terjadi saat menjalankan
            double hargaobat = Double.parseDouble(tftotal.getText()); // dri string dirubah ke dobel,agar bisa dihitung
            double uangmasuk = Double.parseDouble(tfcash.getText()); 
            double kembalian = uangmasuk - hargaobat;
//setalh dihitung dri dobel dikembalikan ke string
            if (kembalian >= 0) {
                tfkembali.setText(String.valueOf(kembalian));
            } else {
                tfkembali.setText("Uang Tidak Cukup");
            }
        } catch (NumberFormatException e) {
            tfkembali.setText("");
        }
        //mengubah tipe string ke numerik,dan jika pengguna memasukkan huruf atau simbol yang bukan angka
        //catch akan menangani eror agar tdk berhenti mendadak
    //misalnya pengguna memasukkan teks non-numerik), maka teks di tfkembali akan direset menjadi kosong
    }
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        panel1 = new javax.swing.JPanel();
        panel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        obat1 = new javax.swing.JRadioButton();
        obat6 = new javax.swing.JRadioButton();
        obat2 = new javax.swing.JRadioButton();
        obat7 = new javax.swing.JRadioButton();
        obat3 = new javax.swing.JRadioButton();
        obat4 = new javax.swing.JRadioButton();
        obat5 = new javax.swing.JRadioButton();
        labelpesan = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        tfjumlah = new javax.swing.JTextField();
        btntambah = new javax.swing.JButton();
        btntotal = new javax.swing.JButton();
        tftotal = new javax.swing.JTextField();
        btnkurang = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        tfcash = new javax.swing.JTextField();
        btnreset = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        tfkembali = new javax.swing.JTextField();
        btncancel = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        panel1.setBackground(new java.awt.Color(255, 153, 153));

        panel2.setBackground(new java.awt.Color(255, 102, 102));

        jPanel5.setBackground(new java.awt.Color(255, 102, 102));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 48)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Apotek");
        jPanel5.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(-80, 0, 350, 161));

        jLabel1.setBackground(new java.awt.Color(255, 102, 102));
        jLabel1.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 48)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Shenny");

        javax.swing.GroupLayout panel2Layout = new javax.swing.GroupLayout(panel2);
        panel2.setLayout(panel2Layout);
        panel2Layout.setHorizontalGroup(
            panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel2Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 481, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(113, Short.MAX_VALUE))
        );
        panel2Layout.setVerticalGroup(
            panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );

        jPanel3.setBackground(new java.awt.Color(255, 51, 51));
        jPanel3.setLayout(new java.awt.GridLayout(5, 2));

        buttonGroup1.add(obat1);
        obat1.setText("Mixagrib Rp. 10.000");
        obat1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pemvismodul3/Mixagrip111.jpeg.jpg"))); // NOI18N
        obat1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                obat1ActionPerformed(evt);
            }
        });
        jPanel3.add(obat1);

        buttonGroup1.add(obat6);
        obat6.setText("paracetamol Rp. 10.000");
        obat6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pemvismodul3/parace111.jpeg.jpg"))); // NOI18N
        obat6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                obat6ActionPerformed(evt);
            }
        });
        jPanel3.add(obat6);

        buttonGroup1.add(obat2);
        obat2.setText("Acitral Rp.10.000");
        obat2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pemvismodul3/acitral111.jpeg.jpg"))); // NOI18N
        obat2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                obat2ActionPerformed(evt);
            }
        });
        jPanel3.add(obat2);

        buttonGroup1.add(obat7);
        obat7.setText("promag Rp.10.000");
        obat7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pemvismodul3/promag111.jpeg.jpg"))); // NOI18N
        obat7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                obat7ActionPerformed(evt);
            }
        });
        jPanel3.add(obat7);

        buttonGroup1.add(obat3);
        obat3.setText("bodrek Rp.10.000");
        obat3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pemvismodul3/bodrex111.jpeg.png"))); // NOI18N
        obat3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                obat3ActionPerformed(evt);
            }
        });
        jPanel3.add(obat3);

        buttonGroup1.add(obat4);
        obat4.setText("cefalexin Rp.10.000");
        obat4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pemvismodul3/cefalexin111.jpeg.jpg"))); // NOI18N
        obat4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                obat4ActionPerformed(evt);
            }
        });
        jPanel3.add(obat4);

        buttonGroup1.add(obat5);
        obat5.setText("Mylanta Rp.10.000");
        obat5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pemvismodul3/mylanta111.jpeg.jpg"))); // NOI18N
        obat5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                obat5ActionPerformed(evt);
            }
        });
        jPanel3.add(obat5);

        labelpesan.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        labelpesan.setText("Pesan Obat");

        jPanel6.setBackground(new java.awt.Color(255, 51, 51));

        jLabel4.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 14)); // NOI18N
        jLabel4.setText("JUMLAH");

        tfjumlah.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        btntambah.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btntambah.setText("+");
        btntambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntambahActionPerformed(evt);
            }
        });

        btntotal.setBackground(new java.awt.Color(204, 255, 255));
        btntotal.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btntotal.setText("Total");
        btntotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntotalActionPerformed(evt);
            }
        });

        tftotal.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        btnkurang.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnkurang.setText("-");
        btnkurang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnkurangActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btntotal, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnkurang, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(tfjumlah, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btntambah, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(tftotal, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(56, 56, 56)))
                .addGap(44, 44, 44))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btntambah, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfjumlah, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnkurang, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btntotal, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tftotal, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel8.setBackground(new java.awt.Color(255, 51, 51));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jLabel5.setText("Cash");
        jPanel8.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, -1, -1));

        tfcash.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel8.add(tfcash, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 90, 30));

        btnreset.setBackground(new java.awt.Color(204, 255, 255));
        btnreset.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnreset.setText("Reset");
        btnreset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnresetActionPerformed(evt);
            }
        });
        jPanel8.add(btnreset, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 90, 30));

        jLabel6.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jLabel6.setText("Kembalian");
        jPanel8.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, -1, -1));

        tfkembali.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel8.add(tfkembali, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 40, 120, 30));

        btncancel.setBackground(new java.awt.Color(204, 255, 255));
        btncancel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btncancel.setText("Cancel");
        btncancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncancelActionPerformed(evt);
            }
        });
        jPanel8.add(btncancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 90, 120, 30));

        jLabel7.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        jLabel7.setText("Pembayaran");

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addComponent(labelpesan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addGap(186, 186, 186))
            .addComponent(panel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 448, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(126, 126, 126))
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelpesan)
                    .addComponent(jLabel7))
                .addGap(1, 1, 1)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 37, Short.MAX_VALUE))
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
        
    }//GEN-LAST:event_formWindowActivated

    private void btnresetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnresetActionPerformed
        // TODO add your handling code here:
        buttonGroup1.clearSelection();//untuk menghapus pilihan yang ada pada grup tombol radio tersebut
        int jumlah = 0;//diinisialisasi dengan nilai 0
        tfjumlah.setText(String.valueOf(jumlah));
        tftotal.setText("");
        tfcash.setText("");
        tfkembali.setText("");
        tftotal.setText("");//mengosongkan teks di field tftotal, 
        //sehingga tidak ada  informasi yang muncul setelah proses ini dijalankan.
    }//GEN-LAST:event_btnresetActionPerformed
//mengubah nilai dari jumlah menjadi string dengan string.value
    private void btntotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntotalActionPerformed
        // TODO add your handling code here:
        // Pengecekan jika tidak ada obat yang dipilih
        if (buttonGroup1.getSelection() == null) {
            JOptionPane.showMessageDialog(null, "Anda harus memilih obat terlebih dahulu!", "Peringatan", JOptionPane.WARNING_MESSAGE);
            return;
        }

        // Pengecekan jika jumlah pesanan tidak valid
        String jumlahpesanan = tfjumlah.getText();
        if (jumlahpesanan.isEmpty() || Integer.parseInt(jumlahpesanan) <= 0) {
            JOptionPane.showMessageDialog(null, "Jumlah pembelian harus lebih dari 0!", "Peringatan", JOptionPane.WARNING_MESSAGE);
            return;
        }
        

        // Mulai penghitungan harga total
        double harga = 0;
//menyimpan harga dalam bentuk bilangan desimal,
        // Menampilkan detail obat berdasarkan yang dipilih
        if (obat1.isSelected()) {
            harga += 10000 * Integer.parseInt(jumlahpesanan);
            //nilai string ini menjadi integer (angka) agar bisa digunakan dalam operasi perhitungan
        }
        tftotal.setText(String.valueOf(harga));

                    
        penghitungan();//digunakan untuk melakukan perhitungan tambahan
        

        if (obat2.isSelected()) {
            harga += 10000 * Integer.parseInt(jumlahpesanan);
        }
        tftotal.setText(String.valueOf(harga));

                    
        penghitungan();//digunakan untuk melakukan perhitungan tambahan

        if (obat3.isSelected()) {
            harga += 10000 * Integer.parseInt(jumlahpesanan);
        }
        tftotal.setText(String.valueOf(harga));

                    
        penghitungan();

        if (obat4.isSelected()) {
            harga += 10000 * Integer.parseInt(jumlahpesanan);
        }
        tftotal.setText(String.valueOf(harga));

                    
        penghitungan();

        if (obat5.isSelected()) {
            harga += 10000 * Integer.parseInt(jumlahpesanan);
        }
        tftotal.setText(String.valueOf(harga));

                    
        penghitungan();

        if (obat6.isSelected()) {
            harga += 10000 * Integer.parseInt(jumlahpesanan);
        }
        tftotal.setText(String.valueOf(harga));

                    
        penghitungan();

        if (obat7.isSelected()) {
            harga += 10000 * Integer.parseInt(jumlahpesanan);
        }
        tftotal.setText(String.valueOf(harga));

                    
        penghitungan();


        
    }//GEN-LAST:event_btntotalActionPerformed

    private void btntambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntambahActionPerformed
        // TODO add your handling code here:
        int jumlah = Integer.parseInt(tfjumlah.getText());//mengambil teks yang ada di input field
        //mengonversi string tersebut menjadi bilangan bulat (int
        jumlah += 1;//Ini berarti setiap kali kode ini dijalankan, nilai jumlah akan bertambah 1.
        tfjumlah.setText(String.valueOf(jumlah));
        //dirubah lagi ke string agar bisa ditampilkan
    }//GEN-LAST:event_btntambahActionPerformed

    private void btnkurangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnkurangActionPerformed
        // TODO add your handling code here:
        if(Integer.parseInt(tfjumlah.getText())>0)
        {
        int jumlah = Integer.parseInt(tfjumlah.getText());
            jumlah -= 1;
            tfjumlah.setText(String.valueOf(jumlah));
        }else{
            tfjumlah.setText("0");//menetapkan teks di dalam komponen tfjumlah menjadi "0".
        }
    }//GEN-LAST:event_btnkurangActionPerformed

    private void obat1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_obat1ActionPerformed
        // TODO add your handling code here:
        String detailObat = "Mixagrib: \nHarga: 10000\nDeskripsi: Meredakan sakit kepala,Fllu: 500 mg setiap 4-6 jam";
        JOptionPane.showMessageDialog(null, detailObat, "Detail Obat:", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_obat1ActionPerformed

    private void obat2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_obat2ActionPerformed
        // TODO add your handling code here:
        String detailObat = "Acitral: \nHarga: 10000\nDeskripsi: bermanfaat untuk meredakan gejala maag\nDosis: 500 mg 3 kali sehari selama 7 hari";
        JOptionPane.showMessageDialog(null, detailObat, "Detail Obat:", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_obat2ActionPerformed

    private void obat3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_obat3ActionPerformed
        // TODO add your handling code here:
        String detailObat = "Bodrex: \nHarga: 10000\nDeskripsi: bermanfaat untuk meringankan sakit kepala, sakit gigi, dan menurunkan demam\nDosis: 10 mg sekali sehari";
        JOptionPane.showMessageDialog(null, detailObat, "Detail Obat:", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_obat3ActionPerformed

    private void obat4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_obat4ActionPerformed
        // TODO add your handling code here:
         String detailObat = "cefalexin: \nHarga: 10000\nDeskripsi: mengobati penyakit infeksi yang disebabkan oleh infeksi bakteri, seperti Staphylococcus aureus, Streptococcus pneumoniae, Haemophilus influenzae, atau Escherichia coli.\nDosis: 400-600 mg setiap 6-8 jam";
         JOptionPane.showMessageDialog(null, detailObat, "Detail Obat:", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_obat4ActionPerformed

    private void obat5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_obat5ActionPerformed
        // TODO add your handling code here:
        String detailObat = "Mylanta: \nHarga: 10000\nDeskripsi: Meredakan asam lambung, magh, dan sejenis sakit lambung \nDosis: 1-2 tablet saat gejala muncul";
        JOptionPane.showMessageDialog(null, detailObat, "Detail Obat:", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_obat5ActionPerformed

    private void obat6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_obat6ActionPerformed
        // TODO add your handling code here:
        String detailObat = "Paracetamol: \nHarga: 10000\nDeskripsi: Meredakan demam dan nyeri pada kepala dan yang lainnya\nDosis: 10 mg sekali sehari";
        JOptionPane.showMessageDialog(null, detailObat, "Detail Obat 6", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_obat6ActionPerformed

    private void obat7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_obat7ActionPerformed
        // TODO add your handling code here:
        String detailObat = "promag: \nHarga: 10000\nDeskripsi: mengobati gejala magh dan sejenis sakit pada lambung yang belum terlalu parah.\nDosis: 0.5-4 mg per hari";
        JOptionPane.showMessageDialog(null, detailObat, "Detail Obat:", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_obat7ActionPerformed

    private void btncancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncancelActionPerformed
        // TODO add your handling code here:
        int keluar = JOptionPane.showConfirmDialog(null, "Anda Yakin Ingin Keluar Program?", 
                                                   "Keluar", JOptionPane.YES_NO_OPTION, 
                                                   JOptionPane.QUESTION_MESSAGE);
        if (keluar == JOptionPane.YES_OPTION) {
            System.exit(0); //menghentikan program dan keluar dari aplikasi 
        }
    }//GEN-LAST:event_btncancelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ApotekMini.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ApotekMini.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ApotekMini.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ApotekMini.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ApotekMini().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btncancel;
    private javax.swing.JButton btnkurang;
    private javax.swing.JButton btnreset;
    private javax.swing.JButton btntambah;
    private javax.swing.JButton btntotal;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JLabel labelpesan;
    private javax.swing.JRadioButton obat1;
    private javax.swing.JRadioButton obat2;
    private javax.swing.JRadioButton obat3;
    private javax.swing.JRadioButton obat4;
    private javax.swing.JRadioButton obat5;
    private javax.swing.JRadioButton obat6;
    private javax.swing.JRadioButton obat7;
    private javax.swing.JPanel panel1;
    private javax.swing.JPanel panel2;
    private javax.swing.JTextField tfcash;
    private javax.swing.JTextField tfjumlah;
    private javax.swing.JTextField tfkembali;
    private javax.swing.JTextField tftotal;
    // End of variables declaration//GEN-END:variables
}
