/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pemvismodul3;

import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Lavilia
 */
public class PembayaranSPP extends javax.swing.JFrame { // subclass dari JFrame.
    //igunakan untuk menandai apakah pembayaran untuk bulan tertentu telah dilakukan atau belum
    boolean[] statusPembayaranBulan = new boolean[12];
    private String namaSiswa = "";
    private String kelasSiswa = "";
    private String nisnSiswa = "";

    /**
     * Creates new form PembayaranSPP
     */
    
    public PembayaranSPP() {
        initComponents();
        tfpmbyrn.addKeyListener(new KeyAdapter() {
            public void keyReleased(KeyEvent e) {
                penghitungan();
            }
        });
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private void penghitungan() {
        try { //menangkap kemungkinan error yang terjadi saat menjalankan
            double pembayaran = Double.parseDouble(tftotal.getText()); // dri string dirubah ke dobel,agar bisa dihitung
            double uangmasuk = Double.parseDouble(tfpmbyrn.getText()); 
            double kembalian = uangmasuk - pembayaran;

            if (kembalian >= 0) {
                tfkembali.setText(String.valueOf(kembalian)); // Menampilkan kembalian
            } else {
                tfkembali.setText("Uang Tidak Cukup"); // Jika uang kurang
            }
        } catch (NumberFormatException e) {
            tfkembali.setText(""); 
        }
    }
    //mengubah tipe string ke numerik,dan jika pengguna memasukkan huruf atau simbol yang bukan angka
    //catch akan menangani eror agar tdk berhenti mendadak
    //misalnya pengguna memasukkan teks non-numerik), maka teks di tfkembali akan direset menjadi kosong
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel1 = new javax.swing.JPanel();
        panel2 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        panel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tfnama = new javax.swing.JTextField();
        tfkelas = new javax.swing.JTextField();
        tfnisn = new javax.swing.JTextField();
        btndata = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        panel4 = new javax.swing.JPanel();
        panel5 = new javax.swing.JPanel();
        januari = new javax.swing.JCheckBox();
        februari = new javax.swing.JCheckBox();
        maret = new javax.swing.JCheckBox();
        april = new javax.swing.JCheckBox();
        mei = new javax.swing.JCheckBox();
        juni = new javax.swing.JCheckBox();
        juli = new javax.swing.JCheckBox();
        agustus = new javax.swing.JCheckBox();
        september = new javax.swing.JCheckBox();
        oktober = new javax.swing.JCheckBox();
        november = new javax.swing.JCheckBox();
        desember = new javax.swing.JCheckBox();
        jLabel7 = new javax.swing.JLabel();
        tfpmbyrn = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        tfkembali = new javax.swing.JTextField();
        btntotal = new javax.swing.JButton();
        tftotal = new javax.swing.JTextField();
        btnpmbyrn = new javax.swing.JButton();
        btnstatus = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabelstatus = new javax.swing.JTable();
        btnbatal = new javax.swing.JButton();
        btnkeluar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panel1.setBackground(new java.awt.Color(0, 0, 255));
        panel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel2.setBackground(new java.awt.Color(51, 153, 255));

        jLabel10.setBackground(new java.awt.Color(51, 153, 255));
        jLabel10.setFont(new java.awt.Font("Chaparral Pro", 1, 48)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("SMAN 1 BOJONEGORO");
        panel2.add(jLabel10);

        panel1.add(panel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1105, -1));

        panel3.setBackground(new java.awt.Color(102, 153, 255));

        jLabel2.setFont(new java.awt.Font("Adobe Fan Heiti Std B", 0, 12)); // NOI18N
        jLabel2.setText("Nama:");

        jLabel3.setFont(new java.awt.Font("Adobe Fan Heiti Std B", 0, 12)); // NOI18N
        jLabel3.setText("Kelas:");

        jLabel5.setFont(new java.awt.Font("Adobe Fan Heiti Std B", 0, 12)); // NOI18N
        jLabel5.setText("NISN:");

        tfnama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfnamaActionPerformed(evt);
            }
        });

        tfkelas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfkelasActionPerformed(evt);
            }
        });

        tfnisn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfnisnActionPerformed(evt);
            }
        });

        btndata.setBackground(new java.awt.Color(153, 204, 255));
        btndata.setFont(new java.awt.Font("Adobe Fan Heiti Std B", 0, 14)); // NOI18N
        btndata.setText("Kirim");
        btndata.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndataActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel3Layout = new javax.swing.GroupLayout(panel3);
        panel3.setLayout(panel3Layout);
        panel3Layout.setHorizontalGroup(
            panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel3Layout.createSequentialGroup()
                        .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfnisn, javax.swing.GroupLayout.DEFAULT_SIZE, 285, Short.MAX_VALUE)
                            .addComponent(tfkelas)
                            .addComponent(tfnama))
                        .addContainerGap())
                    .addGroup(panel3Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btndata)
                .addContainerGap())
        );
        panel3Layout.setVerticalGroup(
            panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(tfnama, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfkelas, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(5, 5, 5)
                .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfnisn, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btndata, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4))
        );

        panel1.add(panel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 163, -1, -1));

        jLabel1.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Data Siswa");
        panel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(159, 128, 83, -1));

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 14)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Loket Pembayaran");
        panel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(789, 128, 220, -1));

        panel4.setBackground(new java.awt.Color(0, 153, 255));

        panel5.setBackground(new java.awt.Color(0, 102, 255));
        panel5.setLayout(new java.awt.GridLayout(2, 6));

        januari.setFont(new java.awt.Font("Adobe Fan Heiti Std B", 0, 12)); // NOI18N
        januari.setText("Januari");
        panel5.add(januari);

        februari.setFont(new java.awt.Font("Adobe Fan Heiti Std B", 0, 12)); // NOI18N
        februari.setText("Februari");
        februari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                februariActionPerformed(evt);
            }
        });
        panel5.add(februari);

        maret.setFont(new java.awt.Font("Adobe Fan Heiti Std B", 0, 12)); // NOI18N
        maret.setText("Maret");
        panel5.add(maret);

        april.setFont(new java.awt.Font("Adobe Fan Heiti Std B", 0, 12)); // NOI18N
        april.setText("April");
        panel5.add(april);

        mei.setFont(new java.awt.Font("Adobe Fan Heiti Std B", 0, 12)); // NOI18N
        mei.setText("Mei");
        mei.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                meiActionPerformed(evt);
            }
        });
        panel5.add(mei);

        juni.setFont(new java.awt.Font("Adobe Fan Heiti Std B", 0, 12)); // NOI18N
        juni.setText("Juni");
        juni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                juniActionPerformed(evt);
            }
        });
        panel5.add(juni);

        juli.setFont(new java.awt.Font("Adobe Fan Heiti Std B", 0, 12)); // NOI18N
        juli.setText("Juli");
        panel5.add(juli);

        agustus.setFont(new java.awt.Font("Adobe Fan Heiti Std B", 0, 12)); // NOI18N
        agustus.setText("Agustus");
        panel5.add(agustus);

        september.setFont(new java.awt.Font("Adobe Fan Heiti Std B", 0, 12)); // NOI18N
        september.setText("September");
        panel5.add(september);

        oktober.setFont(new java.awt.Font("Adobe Fan Heiti Std B", 0, 12)); // NOI18N
        oktober.setText("Oktober");
        panel5.add(oktober);

        november.setFont(new java.awt.Font("Adobe Fan Heiti Std B", 0, 12)); // NOI18N
        november.setText("November");
        november.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                novemberActionPerformed(evt);
            }
        });
        panel5.add(november);

        desember.setFont(new java.awt.Font("Adobe Fan Heiti Std B", 0, 12)); // NOI18N
        desember.setText("Desember");
        panel5.add(desember);

        jLabel7.setFont(new java.awt.Font("Adobe Fan Heiti Std B", 1, 14)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Pilihan Bulan");

        tfpmbyrn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfpmbyrnActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Pembayaran");

        jLabel9.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        jLabel9.setText("Kembalian");

        tfkembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfkembaliActionPerformed(evt);
            }
        });

        btntotal.setBackground(new java.awt.Color(204, 204, 255));
        btntotal.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        btntotal.setText("Hitung Pembayaran");
        btntotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntotalActionPerformed(evt);
            }
        });

        btnpmbyrn.setBackground(new java.awt.Color(204, 204, 255));
        btnpmbyrn.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 14)); // NOI18N
        btnpmbyrn.setText("Kirim");
        btnpmbyrn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpmbyrnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel4Layout = new javax.swing.GroupLayout(panel4);
        panel4.setLayout(panel4Layout);
        panel4Layout.setHorizontalGroup(
            panel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel4Layout.createSequentialGroup()
                .addGroup(panel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel4Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(panel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btntotal)
                            .addGroup(panel4Layout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addComponent(jLabel8))
                            .addGroup(panel4Layout.createSequentialGroup()
                                .addGap(43, 43, 43)
                                .addComponent(jLabel9))
                            .addGroup(panel4Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(panel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tfpmbyrn, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tftotal, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tfkembali, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(btnpmbyrn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panel4Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(jLabel7)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panel4Layout.setVerticalGroup(
            panel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel4Layout.createSequentialGroup()
                        .addComponent(btntotal, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tftotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfpmbyrn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfkembali, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 89, Short.MAX_VALUE)
                        .addComponent(btnpmbyrn, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(panel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        panel1.add(panel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 163, -1, -1));

        btnstatus.setFont(new java.awt.Font("Adobe Fan Heiti Std B", 1, 14)); // NOI18N
        btnstatus.setText("Status Pembayaran");
        btnstatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnstatusActionPerformed(evt);
            }
        });
        panel1.add(btnstatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(124, 339, -1, 30));

        jScrollPane2.setBackground(new java.awt.Color(102, 153, 255));

        tabelstatus.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        tabelstatus.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Bulan", "Status"
            }
        ));
        jScrollPane2.setViewportView(tabelstatus);

        panel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 387, 341, 159));

        btnbatal.setBackground(new java.awt.Color(204, 204, 255));
        btnbatal.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnbatal.setText("Batal");
        btnbatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbatalActionPerformed(evt);
            }
        });
        panel1.add(btnbatal, new org.netbeans.lib.awtextra.AbsoluteConstraints(442, 512, 84, 35));

        btnkeluar.setBackground(new java.awt.Color(204, 204, 255));
        btnkeluar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnkeluar.setText("Keluar");
        btnkeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnkeluarActionPerformed(evt);
            }
        });
        panel1.add(btnkeluar, new org.netbeans.lib.awtextra.AbsoluteConstraints(971, 512, -1, 35));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void meiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_meiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_meiActionPerformed

    private void februariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_februariActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_februariActionPerformed

    private void novemberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_novemberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_novemberActionPerformed

    private void tfnamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfnamaActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_tfnamaActionPerformed

    private void tfkelasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfkelasActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_tfkelasActionPerformed

    private void btntotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntotalActionPerformed
        // TODO add your handling code here:
        // Pastikan data siswa sudah diisi
        if (namaSiswa.isEmpty() || kelasSiswa.isEmpty() || nisnSiswa.isEmpty()) {
        JOptionPane.showMessageDialog(null, "Harap mengisi data siswa terlebih dahulu!", "Peringatan", JOptionPane.WARNING_MESSAGE);
        return;
        }

        // Periksa dan nonaktifkan checkbox untuk bulan yang sudah lunas
        if (statusPembayaranBulan[0]) {
            januari.setEnabled(false);
            januari.setSelected(false); // Deselect jika sudah lunas
        }
        if (statusPembayaranBulan[1]) {
            februari.setEnabled(false);
            februari.setSelected(false);
        }
        if (statusPembayaranBulan[2]) {
            maret.setEnabled(false);
            maret.setSelected(false);
        }
        if (statusPembayaranBulan[3]) {
            april.setEnabled(false);
            april.setSelected(false);
        }
        if (statusPembayaranBulan[4]) {
            mei.setEnabled(false);
            mei.setSelected(false);
        }
        if (statusPembayaranBulan[5]) {
            juni.setEnabled(false);
            juni.setSelected(false);
        }
        if (statusPembayaranBulan[6]) {
            juli.setEnabled(false);
            juli.setSelected(false);
        }
        if (statusPembayaranBulan[7]) {
            agustus.setEnabled(false);
            agustus.setSelected(false);
        }
        if (statusPembayaranBulan[8]) {
            september.setEnabled(false);
            september.setSelected(false);
        }
        if (statusPembayaranBulan[9]) {
            oktober.setEnabled(false);
            oktober.setSelected(false);
        }
        if (statusPembayaranBulan[10]) {
            november.setEnabled(false);
            november.setSelected(false);
        }
        if (statusPembayaranBulan[11]) {
            desember.setEnabled(false);
            desember.setSelected(false);
        }

        // Lanjutkan dengan logika perhitungan total pembayaran
        try {
            double sppPerBulan = 500000; // Misalkan biaya per bulan
            int jumlahBulanDipilih = 0;

            // memerikasa apakah komponen sudah dipilih atau tidak,menyimpan status pembayarn
            if (januari.isSelected() && !statusPembayaranBulan[0]) jumlahBulanDipilih++;
            if (februari.isSelected() && !statusPembayaranBulan[1]) jumlahBulanDipilih++;
            if (maret.isSelected() && !statusPembayaranBulan[2]) jumlahBulanDipilih++;
            if (april.isSelected() && !statusPembayaranBulan[3]) jumlahBulanDipilih++;
            if (mei.isSelected() && !statusPembayaranBulan[4]) jumlahBulanDipilih++;
            if (juni.isSelected() && !statusPembayaranBulan[5]) jumlahBulanDipilih++;
            if (juli.isSelected() && !statusPembayaranBulan[6]) jumlahBulanDipilih++;
            if (agustus.isSelected() && !statusPembayaranBulan[7]) jumlahBulanDipilih++;
            if (september.isSelected() && !statusPembayaranBulan[8]) jumlahBulanDipilih++;
            if (oktober.isSelected() && !statusPembayaranBulan[9]) jumlahBulanDipilih++;
            if (november.isSelected() && !statusPembayaranBulan[10]) jumlahBulanDipilih++;
            if (desember.isSelected() && !statusPembayaranBulan[11]) jumlahBulanDipilih++;

            // Total yang harus dibayar
            double totalPembayaran = jumlahBulanDipilih * sppPerBulan;
            tftotal.setText(String.valueOf(totalPembayaran));

            // Cek apakah input pembayaran tidak kosong dan valid
            String uangDibayarText = tfpmbyrn.getText().trim();
            if (uangDibayarText.isEmpty()) {
                JOptionPane.showMessageDialog(null, "Harap masukkan jumlah uang yang dibayar!", "Peringatan", JOptionPane.WARNING_MESSAGE);
                return;
            }

            // Parse jumlah uang yang dibayarkan
            double uangDibayar = Double.parseDouble(uangDibayarText);

            // Panggil metode penghitungan untuk menghitung kembalian
            penghitungan();

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Masukkan jumlah uang yang valid!", "Error", JOptionPane.ERROR_MESSAGE);
        }                                      
     //misalnya pengguna memasukkan teks non-numerik), maka teks di tfkembali akan direset 
        
    }//GEN-LAST:event_btntotalActionPerformed

    private void btnstatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnstatusActionPerformed
        // bertujuan untuk memperbarui status pembayaran di tabel yang menunjukkan status pembayaran 
        updateStatusPembayaranTabel();
    }
        private void updateStatusPembayaranTabel() {
        String[] bulan = {"Januari", "Februari", "Maret", "April", "Mei", "Juni", 
                          "Juli", "Agustus", "September", "Oktober", "November", "Desember"};

        DefaultTableModel model = (DefaultTableModel) tabelstatus.getModel();
        model.setRowCount(0);  // untuk memperbarui tabel sesuai dengan status pembayaran siswa

        boolean lunasSemua = true;  // Flag untuk cek status lunas semua bulan
// memproses setiap elemen dalam array untuk mendapatkan status pembayaran untuk masing-masing bulan
        for (int i = 0; i < statusPembayaranBulan.length; i++) {
            String status = statusPembayaranBulan[i] ? "Lunas" : "Belum dibayar";
            model.addRow(new Object[]{bulan[i], status});

            // Cek jika ada bulan yang belum lunas
            if (!statusPembayaranBulan[i]) {
                lunasSemua = false;
            }
        }

        // Tampilkan pesan sesuai status pembayaran
        if (lunasSemua) {
            JOptionPane.showMessageDialog(null, "Pembayaran sudah lunas untuk semua bulan.", "Status Pembayaran", JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(null, "Pembayaran belum lunas. Silakan cek bulan yang belum dibayar.", "Status Pembayaran", JOptionPane.WARNING_MESSAGE);
        }
    
    }//GEN-LAST:event_btnstatusActionPerformed

    private void tfpmbyrnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfpmbyrnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfpmbyrnActionPerformed

    private void tfkembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfkembaliActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfkembaliActionPerformed

    private void btnpmbyrnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpmbyrnActionPerformed
        // TODO add your handling code here:
        // Pastikan pembayaran cukup
        double totalPembayaran = Double.parseDouble(tftotal.getText());
        double uangDibayar = Double.parseDouble(tfpmbyrn.getText());
        if (uangDibayar < totalPembayaran) {
            JOptionPane.showMessageDialog(null, "Pembayaran kurang!", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Update status pembayaran bulan yang dipilih
        if (januari.isSelected()) statusPembayaranBulan[0] = true;
        if (februari.isSelected()) statusPembayaranBulan[1] = true;
        if (maret.isSelected()) statusPembayaranBulan[2] = true;
        if (april.isSelected()) statusPembayaranBulan[3] = true;
        if (mei.isSelected()) statusPembayaranBulan[4] = true;
        if (juni.isSelected()) statusPembayaranBulan[5] = true;
        if (juli.isSelected()) statusPembayaranBulan[6] = true;
        if (agustus.isSelected()) statusPembayaranBulan[7] = true;
        if (september.isSelected()) statusPembayaranBulan[8] = true;
        if (oktober.isSelected()) statusPembayaranBulan[9] = true;
        if (november.isSelected()) statusPembayaranBulan[10] = true;
        if (desember.isSelected()) statusPembayaranBulan[11] = true;

        // Kosongkan semua field setelah data terkirim
        tfpmbyrn.setText("");
        tfkembali.setText("");
        tftotal.setText("");
        januari.setSelected(false); //tombol radio atau checkbox untuk bulan Januari akan tidak terpilih
        februari.setSelected(false);
        maret.setSelected(false);
        april.setSelected(false);
        mei.setSelected(false);
        juni.setSelected(false);
        juli.setSelected(false);
        agustus.setSelected(false);
        september.setSelected(false);
        oktober.setSelected(false);
        november.setSelected(false);
        desember.setSelected(false);

        JOptionPane.showMessageDialog(null, "Pembayaran berhasil dan data telah disimpan.");
    }//GEN-LAST:event_btnpmbyrnActionPerformed

    private void juniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_juniActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_juniActionPerformed

    private void btnkeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnkeluarActionPerformed
        // TODO add your handling code here:
        int pilihan = JOptionPane.showConfirmDialog(null, "Apakah Anda yakin ingin keluar?", "Konfirmasi Keluar", JOptionPane.YES_NO_OPTION);
    
        // Jika pengguna memilih "Yes", program akan ditutup
        if (pilihan == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_btnkeluarActionPerformed

    private void btnbatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbatalActionPerformed
        // TODO add your handling code here:
        januari.setSelected(false);
        februari.setSelected(false);
        maret.setSelected(false);
        april.setSelected(false);
        mei.setSelected(false);
        juni.setSelected(false);
        juli.setSelected(false);
        agustus.setSelected(false);
        september.setSelected(false);
        oktober.setSelected(false);
        november.setSelected(false);
        desember.setSelected(false);

        // Reset total pembayaran
        tftotal.setText("");
        tfpmbyrn.setText("");

        // Tampilkan pesan konfirmasi
        JOptionPane.showMessageDialog(null, "Pilihan pembayaran telah dibatalkan.", "Pembatalan", JOptionPane.INFORMATION_MESSAGE);

    }//GEN-LAST:event_btnbatalActionPerformed

    private void btndataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndataActionPerformed
        // TODO add your handling code here:
        // Ambil data dari field input
        String nama = tfnama.getText();
        String kelas = tfkelas.getText();
        String nisn = tfnisn.getText();
        // Cek apakah semua data siswa sudah diisi
        if (nama.isEmpty() || kelas.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Harap mengisi semua data siswa!");
        } else {
            // Simpan data siswa ke variabel global
            namaSiswa = nama;
            kelasSiswa = kelas;
            nisnSiswa = nisn;
            // Kosongkan field setelah data dikirim
            tfnama.setText("");
            tfkelas.setText("");
            tfnisn.setText("");
            JOptionPane.showMessageDialog(null, "Data siswa berhasil dikirim!");
        }
    }//GEN-LAST:event_btndataActionPerformed

    private void tfnisnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfnisnActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_tfnisnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PembayaranSPP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PembayaranSPP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PembayaranSPP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PembayaranSPP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PembayaranSPP().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox agustus;
    private javax.swing.JCheckBox april;
    private javax.swing.JButton btnbatal;
    private javax.swing.JButton btndata;
    private javax.swing.JButton btnkeluar;
    private javax.swing.JButton btnpmbyrn;
    private javax.swing.JButton btnstatus;
    private javax.swing.JButton btntotal;
    private javax.swing.JCheckBox desember;
    private javax.swing.JCheckBox februari;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JCheckBox januari;
    private javax.swing.JCheckBox juli;
    private javax.swing.JCheckBox juni;
    private javax.swing.JCheckBox maret;
    private javax.swing.JCheckBox mei;
    private javax.swing.JCheckBox november;
    private javax.swing.JCheckBox oktober;
    private javax.swing.JPanel panel1;
    private javax.swing.JPanel panel2;
    private javax.swing.JPanel panel3;
    private javax.swing.JPanel panel4;
    private javax.swing.JPanel panel5;
    private javax.swing.JCheckBox september;
    private javax.swing.JTable tabelstatus;
    private javax.swing.JTextField tfkelas;
    private javax.swing.JTextField tfkembali;
    private javax.swing.JTextField tfnama;
    private javax.swing.JTextField tfnisn;
    private javax.swing.JTextField tfpmbyrn;
    private javax.swing.JTextField tftotal;
    // End of variables declaration//GEN-END:variables
}
