/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package modul5;
import java.util.List;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import java.awt.event.ActionListener;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author YOSEY
 */
public class mod5 extends javax.swing.JFrame {
    private DefaultTableModel model1;
    private DefaultTableModel model2;
    private DefaultTableModel model3;
    private TBKaryawan Karyawan = new TBKaryawan();
    private TBProyek proyek = new TBProyek();
    private TBTransaksi transaksi = new TBTransaksi();
    
    //private transaksi = new Transaksi();
    /**
     * Creates new form mod5
     */
    public mod5() {
        initComponents();
        
        model1 = new DefaultTableModel(new String[]{"ID", "Nama", "Jabatan", "Departemen"}, 0);
        model2 = new DefaultTableModel(new String[]{"ID", "Nama_Proyek", "Durasi_pengerjaan"}, 0);
        model3 = new DefaultTableModel(new String[]{"ID_Karyawan", "ID Proyek", "Jobdesk", "Durasi"}, 0);
       
        
        loadKaryawan();
        loadproyek();
        loadTransaksi();
//        comboboxTransaksi();        
        
        TBKaryawan.getSelectionModel().addListSelectionListener(event -> {
            int selectedRow = TBKaryawan.getSelectedRow();
            if (selectedRow != -1) {
                tfidkary.setText(model1.getValueAt(selectedRow, 0).toString());
                tfnmkary.setText(model1.getValueAt(selectedRow, 1).toString());
                cbjabatan.setSelectedItem(model1.getValueAt(selectedRow, 2).toString());
                cbdepart.setSelectedItem(model1.getValueAt(selectedRow, 3).toString());
            }
        });

        TBProyek.getSelectionModel().addListSelectionListener(event -> {
            int selectedRow = TBProyek.getSelectedRow();
            if (selectedRow != -1) {
                tfidpry.setText(model2.getValueAt(selectedRow, 0).toString());
                tfnmpry.setText(model2.getValueAt(selectedRow, 1).toString());
                tfdurasi.setText(model2.getValueAt(selectedRow, 2).toString());
            }
        });

        TBTransaksi.getSelectionModel().addListSelectionListener(event -> {
            int selectedRow = TBTransaksi.getSelectedRow();
            if (selectedRow != -1) {
                cbidkary.setSelectedItem(model3.getValueAt(selectedRow, 0).toString());
                cbidpry.setSelectedItem(model3.getValueAt(selectedRow, 1).toString());
                tfjobdesk.setText(model3.getValueAt(selectedRow, 2).toString());
                tfdur.setText(model3.getValueAt(selectedRow, 3).toString());
            }
        });
    }    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        tfidkary = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        tfnmkary = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        cbjabatan = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        cbdepart = new javax.swing.JComboBox<>();
        jPanel9 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        btntmbhkary = new javax.swing.JButton();
        btneditkary = new javax.swing.JButton();
        btnhpskary = new javax.swing.JButton();
        btnexitkary = new javax.swing.JButton();
        btnclearkary = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        TBKaryawan = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        tfidpry = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        tfnmpry = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        tfdurasi = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        tmbhproyek = new javax.swing.JButton();
        hpsproyek = new javax.swing.JButton();
        editproyek = new javax.swing.JButton();
        exitproyek = new javax.swing.JButton();
        clearproyek = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        TBProyek = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        cbidkary = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        cbidpry = new javax.swing.JComboBox<>();
        tfjobdesk = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        tmbhtransaksi = new javax.swing.JButton();
        hpstransaksi = new javax.swing.JButton();
        cleartransaksi = new javax.swing.JButton();
        edittransaksi = new javax.swing.JButton();
        exittransaksi = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        TBTransaksi = new javax.swing.JTable();
        jLabel15 = new javax.swing.JLabel();
        tfdur = new javax.swing.JTextField();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(255, 204, 102));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setFont(new java.awt.Font("Wide Latin", 1, 24)); // NOI18N
        jLabel1.setText("APLIKASI PROYEK");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 482, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(113, 113, 113))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));

        jTabbedPane1.setBackground(new java.awt.Color(255, 204, 153));
        jTabbedPane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTabbedPane1.setFont(new java.awt.Font("Rockwell Extra Bold", 0, 18)); // NOI18N

        jPanel1.setBackground(new java.awt.Color(255, 255, 102));

        jLabel4.setText("ID Karyawan : ");

        jLabel5.setText("Nama :");

        jLabel7.setText("Jabatan : ");

        cbjabatan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--PILIH--", "Supervisor", "Manager", "Karyawan", "Recepcionist", "Cleaning Servis", "Customer Service", "Security", " " }));

        jLabel2.setText("Departemen : ");

        cbdepart.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--PILIH--", "Front Office", "Housekeeping", "Security", "Marketing", " " }));

        jPanel9.setBackground(new java.awt.Color(255, 153, 0));

        jLabel14.setBackground(new java.awt.Color(255, 102, 0));
        jLabel14.setFont(new java.awt.Font("Castellar", 1, 36)); // NOI18N
        jLabel14.setText("DATA KARYAWAN");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel14)
                .addGap(150, 150, 150))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel14)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel10.setLayout(new java.awt.GridLayout(3, 2));

        btntmbhkary.setText("Tambah");
        btntmbhkary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntmbhkaryActionPerformed(evt);
            }
        });
        jPanel10.add(btntmbhkary);

        btneditkary.setText("Edit");
        btneditkary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneditkaryActionPerformed(evt);
            }
        });
        jPanel10.add(btneditkary);

        btnhpskary.setText("Hapus");
        btnhpskary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhpskaryActionPerformed(evt);
            }
        });
        jPanel10.add(btnhpskary);

        btnexitkary.setText("Exit");
        btnexitkary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnexitkaryActionPerformed(evt);
            }
        });
        jPanel10.add(btnexitkary);

        btnclearkary.setText("Clear");
        btnclearkary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnclearkaryActionPerformed(evt);
            }
        });
        jPanel10.add(btnclearkary);

        TBKaryawan.setBackground(new java.awt.Color(255, 153, 102));
        TBKaryawan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null}
            },
            new String [] {
                "ID Karyawan", "Nama", "Jabatan", "Departemen"
            }
        ));
        jScrollPane3.setViewportView(TBKaryawan);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel7)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4))
                .addGap(53, 53, 53)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tfnmkary, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfidkary, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbjabatan, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbdepart, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(62, 62, 62)
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(38, Short.MAX_VALUE))
            .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane3)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(tfidkary, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(40, 40, 40)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(tfnmkary, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(49, 49, 49)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(cbjabatan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(56, 56, 56))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cbdepart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(72, 72, 72))
        );

        jTabbedPane1.addTab("Karyawan", jPanel1);

        jPanel3.setBackground(new java.awt.Color(255, 255, 102));

        jLabel3.setText("ID Proyek : ");

        jLabel6.setText("Nama Proyek :");

        jLabel8.setText("Durasi Pengerjaan : ");

        tfdurasi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfdurasiActionPerformed(evt);
            }
        });

        jPanel6.setBackground(new java.awt.Color(255, 153, 0));

        jLabel13.setBackground(new java.awt.Color(255, 153, 0));
        jLabel13.setFont(new java.awt.Font("Castellar", 1, 36)); // NOI18N
        jLabel13.setText("PROYEK ");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(255, 255, 255)
                .addComponent(jLabel13)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel8.setLayout(new java.awt.GridLayout(2, 3));

        tmbhproyek.setText("Tambah");
        tmbhproyek.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tmbhproyekActionPerformed(evt);
            }
        });
        jPanel8.add(tmbhproyek);

        hpsproyek.setText("Hapus");
        hpsproyek.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hpsproyekActionPerformed(evt);
            }
        });
        jPanel8.add(hpsproyek);

        editproyek.setText("Edit");
        editproyek.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editproyekActionPerformed(evt);
            }
        });
        jPanel8.add(editproyek);

        exitproyek.setText("Exit");
        exitproyek.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitproyekActionPerformed(evt);
            }
        });
        jPanel8.add(exitproyek);

        clearproyek.setText("Clear");
        clearproyek.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearproyekActionPerformed(evt);
            }
        });
        jPanel8.add(clearproyek);

        TBProyek.setBackground(new java.awt.Color(255, 153, 102));
        TBProyek.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null}
            },
            new String [] {
                "ID Proyek", "Nama Proyek", "Durasi Pengerjaan"
            }
        ));
        jScrollPane4.setViewportView(TBProyek);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(101, 101, 101)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel6)
                    .addComponent(jLabel8))
                .addGap(37, 37, 37)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tfnmpry, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                    .addComponent(tfdurasi)
                    .addComponent(tfidpry))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tfidpry, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(tfnmpry, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(47, 47, 47)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(tfdurasi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jTabbedPane1.addTab("Proyek", jPanel3);

        jPanel4.setBackground(new java.awt.Color(255, 255, 102));

        jLabel9.setText("ID Karyawan :");

        jLabel10.setText("ID Proyek :");

        jLabel11.setText("Peran :");

        jPanel5.setBackground(new java.awt.Color(255, 153, 0));

        jLabel12.setFont(new java.awt.Font("Castellar", 1, 36)); // NOI18N
        jLabel12.setText("TRANSAKSI PROYEK");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(125, Short.MAX_VALUE)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 441, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(121, 121, 121))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(0, 11, Short.MAX_VALUE)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel11.setLayout(new java.awt.GridLayout(2, 3));

        tmbhtransaksi.setText("Tambah");
        tmbhtransaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tmbhtransaksiActionPerformed(evt);
            }
        });
        jPanel11.add(tmbhtransaksi);

        hpstransaksi.setText("Hapus");
        hpstransaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hpstransaksiActionPerformed(evt);
            }
        });
        jPanel11.add(hpstransaksi);

        cleartransaksi.setText("Clear");
        cleartransaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cleartransaksiActionPerformed(evt);
            }
        });
        jPanel11.add(cleartransaksi);

        edittransaksi.setText("Edit");
        edittransaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edittransaksiActionPerformed(evt);
            }
        });
        jPanel11.add(edittransaksi);

        exittransaksi.setText("Exit");
        exittransaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exittransaksiActionPerformed(evt);
            }
        });
        jPanel11.add(exittransaksi);

        TBTransaksi.setBackground(new java.awt.Color(255, 153, 102));
        TBTransaksi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null}
            },
            new String [] {
                "ID Karyawan", "ID Proyek", "Jobdesk", "Durasi"
            }
        ));
        jScrollPane5.setViewportView(TBTransaksi);

        jLabel15.setText("Durasi : ");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jScrollPane5)
                .addContainerGap())
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(94, 94, 94)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11)
                    .addComponent(jLabel9)
                    .addComponent(jLabel15))
                .addGap(68, 68, 68)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cbidkary, 0, 164, Short.MAX_VALUE)
                    .addComponent(tfjobdesk)
                    .addComponent(cbidpry, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tfdur))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(cbidkary, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(34, 34, 34)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(cbidpry, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(tfjobdesk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(tfdur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(107, 107, 107)))
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(158, 158, 158))
        );

        jTabbedPane1.addTab("Transaksi Proyek", jPanel4);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 694, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 559, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(326, 326, 326))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void comboboxTransaksi() {
        try {
            List<Karyawan> list_Karyawan = Karyawan.getAllKaryawan();
            cbidkary.addItem("ID | Nama");
            for (Karyawan kry : list_Karyawan) {
                cbidkary.addItem(
                    kry.getID() + " | " +
                    kry.getNama_karyawan()
                );
            }
            List<proyek> list_proyek = proyek.getAllproyek();
            cbidpry.addItem("ID | Nama");
            for (proyek pry : list_proyek) {
                cbidpry.addItem(
                    pry.getID_proyek() + " | " +
                    pry.getNama_proyek()
                );
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Tidak dapat memuat data, error: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }
    private void loadKaryawan() {
        model1.setRowCount(0);
        try {
            List<Karyawan> list_Karyawan = Karyawan.getAllKaryawan();
            
            for (Karyawan kry: list_Karyawan) {
                model1.addRow(
                    new Object[]{
                       kry.getID(),
                       kry.getNama_karyawan(),
                       kry.getJabatan(),
                       kry.getDepartemen()
                    }
            );
        }
            
        TBKaryawan.setModel(model1);
        
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Tidak dapat memuat data, error: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }
    private void btntmbhkaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntmbhkaryActionPerformed
        String id_karyawan = tfidkary.getText();
        String nama_karyawan = tfnmkary.getText();
        String jabatan = cbjabatan.getSelectedItem().toString();
        String departemen = cbdepart.getSelectedItem().toString();
    
        if(jabatan.equals("--PILIH--")|| jabatan.equals("--PILIH--")){
            JOptionPane.showMessageDialog(this, "PILIH TERLEBIH DAHULU", "DISCLAIMER!!!", JOptionPane.WARNING_MESSAGE);
        } else {
            int id = 0;
            try {
                id = Integer.parseInt(id_karyawan);
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(null, "Durasi harus berupa angka valid, error: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }

            Karyawan kry = new Karyawan(
                id,           
                nama_karyawan,
                jabatan,
                departemen
            );

            try {
                Karyawan.InsertKaryawan(kry);
                loadKaryawan();
                comboboxTransaksi(); 
                JOptionPane.showMessageDialog(null, "Data Berhasil Disimpan", "Informasi", JOptionPane.INFORMATION_MESSAGE);
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(null, "Tidak dapat menambahkan proyek, error: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
        
    // TODO add your handling code here:
    }//GEN-LAST:event_btntmbhkaryActionPerformed
    private void btneditkaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneditkaryActionPerformed
        int selectedRow = TBKaryawan.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(null, "Pilih Baris yang akan diubah", "Peringatan", JOptionPane.WARNING_MESSAGE);
            return;
        }

        // Mendapatkan nilai ID dari tabel dan memeriksa apakah nilainya tidak kosong
        Object idValue = model1.getValueAt(selectedRow, 0);
        if (idValue == null || idValue.toString().isEmpty()) {
            JOptionPane.showMessageDialog(null, "ID tidak valid atau kosong.", "Peringatan", JOptionPane.WARNING_MESSAGE);
            return;
        }

        try {
            int id = Integer.parseInt(idValue.toString());
            String nama = tfnmkary.getText();
            String jabatan = (String) cbjabatan.getSelectedItem();
            String dapartemen = (String) cbdepart.getSelectedItem();

            // Membuat objek Barang dengan data yang diperbarui
            Karyawan kry = new Karyawan(id, nama, jabatan, dapartemen);

            // Mengupdate data barang
            try {
                Karyawan.updateKaryawan(kry);
                loadKaryawan(); 
                JOptionPane.showMessageDialog(null, "Data berhasil diubah", "Informasi", JOptionPane.INFORMATION_MESSAGE);
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(null, "Tidak dapat mengubah data, error: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            }
        } catch (NumberFormatException e) {
            System.out.println("ID tidak valid: " + e.getMessage());
        }// TODO add your handling code here:
    }//GEN-LAST:event_btneditkaryActionPerformed
    private void btnhpskaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhpskaryActionPerformed
        int selectedRow = TBKaryawan.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(null, "Piih baris yang akan dihapus", "Peringatan", JOptionPane.WARNING_MESSAGE);
            return;
        }

        try {
            int id = (int) model1.getValueAt(selectedRow, 0);
            List<transaksi> list_transaksi = transaksi.cariData(id);
            if (list_transaksi.isEmpty()) {
                Karyawan.deleteKaryawan(id);
                loadKaryawan();
                JOptionPane.showMessageDialog(null, "Data berhasil dihapus", "Informasi", JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(null, "Data tidak bisa dihapus", "Informasi", JOptionPane.INFORMATION_MESSAGE);
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Tidak dapat menghapus data, error: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnhpskaryActionPerformed
    private void btnexitkaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnexitkaryActionPerformed
        this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_btnexitkaryActionPerformed
    private void btnclearkaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnclearkaryActionPerformed
        tfnmkary.setText("");
        cbjabatan.setSelectedIndex(0);
        cbdepart.setSelectedIndex(0);
        tfidkary.setText("");
        
    }//GEN-LAST:event_btnclearkaryActionPerformed
    private void tmbhproyekActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tmbhproyekActionPerformed
        String id = tfidpry.getText();
        String durasi_pengerjaan = tfdurasi.getText();
        String nama_proyek = tfnmpry.getText();
        
        int durasi = 0;
        
        try {
            // Konversi val_durasi ke int jika tidak kosong
            if (!durasi_pengerjaan.isEmpty()) {
                durasi = Integer.parseInt(durasi_pengerjaan);
            } else {
                JOptionPane.showMessageDialog(null, "Durasi tidak boleh kosong.", "Peringatan", JOptionPane.WARNING_MESSAGE);
                return;
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Durasi harus berupa angka valid, error: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        proyek pry = new proyek(
            0,             
            nama_proyek,
            durasi
        );

        try {
            proyek.Insertproyek(pry);
            loadproyek();
            comboboxTransaksi(); 
            JOptionPane.showMessageDialog(null, "Data Berhasil Disimpan", "Informasi", JOptionPane.INFORMATION_MESSAGE);
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Tidak dapat menambahkan proyek, error: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }// TODO add your handling code here:
    }//GEN-LAST:event_tmbhproyekActionPerformed
    private void hpsproyekActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hpsproyekActionPerformed
        int selectedRow = TBProyek.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(null, "Pilih Baris yang akan dihapus", "Peringatan", JOptionPane.WARNING_MESSAGE);
            return;
        }

        try {
            int id = (int) model2.getValueAt(selectedRow, 0);
            List<transaksi> list_transaksi = transaksi.cariData(id);
            if (list_transaksi.isEmpty()) {
//                proyek.deleteProyek(id);
//                loadproyek();
                JOptionPane.showMessageDialog(null, "Data berhasil dihapus", "Informasi", JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(null, "Data tidak bisa dihapus", "Informasi", JOptionPane.INFORMATION_MESSAGE);
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Tidak dapat menghapus data, error: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_hpsproyekActionPerformed

    private void editproyekActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editproyekActionPerformed
        int selectedRow = TBProyek.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(null, "Pilih baris yang akan diubah", "Peringatan", JOptionPane.WARNING_MESSAGE);
            return;
        }

        Object idValue = model2.getValueAt(selectedRow, 0);

        if (idValue == null || idValue.toString().isEmpty()) {
            JOptionPane.showMessageDialog(null, "ID tidak valid atau kosong.", "Peringatan", JOptionPane.WARNING_MESSAGE);
            return;
        }

        try {
            int id = Integer.parseInt(idValue.toString());
            int durasi_pengerjaan = Integer.parseInt(tfdurasi.getText());  
            String nama_proyek = tfnmpry.getText();


            proyek pry = new proyek(id, nama_proyek, durasi_pengerjaan);

            // Mengupdate data proyek di database
            try {
                proyek.updateProyek(pry);
                loadproyek();
                JOptionPane.showMessageDialog(null, "Data berhasil diubah", "Informasi", JOptionPane.INFORMATION_MESSAGE);
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(null, "Tidak dapat mengubah data, error: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            }
        } catch (NumberFormatException e) {
            System.out.println("ID atau Durasi tidak valid: " + e.getMessage());
        }// TODO add your handling code here:
    }//GEN-LAST:event_editproyekActionPerformed
    private void exitproyekActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitproyekActionPerformed
        this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_exitproyekActionPerformed
    private void clearproyekActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearproyekActionPerformed
        tfnmpry.setText("");
        tfdurasi.setText("");
        tfidpry.setText("");// TODO add your handling code here:
    }//GEN-LAST:event_clearproyekActionPerformed
     public void loadproyek() {
        model2.setRowCount(0);
        List<proyek> list_proyek = null;
        try {
            list_proyek = proyek.getAllproyek();
        } catch (SQLException ex) {
            Logger.getLogger(mod5.class.getName()).log(Level.SEVERE, null, ex);
        }
        for (proyek pry: list_proyek) {
            model2.addRow(
                    new Object[]{
                        pry.getID_proyek(),
                        pry.getNama_proyek(),
                        pry.getDurasi_pengerjaan(),
                    }
            );
        }
          TBProyek.setModel(model2);
//        proyek.setModel(model2);
    }    
    private void tmbhtransaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tmbhtransaksiActionPerformed
        String idkaryawan = cbidkary.getSelectedItem().toString().split(" | ")[0];
        String idproyek = cbidpry.getSelectedItem().toString().split(" | ")[0];
        String jobdesk = tfjobdesk.getText();
        String durasi = tfdur.getText();

        int idKaryawan = Integer.parseInt(idkaryawan);
        int idProyek = Integer.parseInt(idproyek);

        transaksi trs = new transaksi(
            idKaryawan,
            idProyek,
            jobdesk,
            durasi
        );

        try {
            transaksi.InsertTransaksi(trs);
            loadTransaksi(); 
            JOptionPane.showMessageDialog(null, "Data berhasil disimpan", "Informasi", JOptionPane.INFORMATION_MESSAGE);
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Tidak dapat menambahkan data, error: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }// TODO add your handling code here:
    }//GEN-LAST:event_tmbhtransaksiActionPerformed
    private void hpstransaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hpstransaksiActionPerformed
        int selectedRow = TBTransaksi.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(null, "Pilih Baris yang akan dihapus", "Peringatan", JOptionPane.WARNING_MESSAGE);
            return;
        }

        int id_karyawan = (int) model3.getValueAt(selectedRow, 0);
        int id_proyek = (int) model3.getValueAt(selectedRow, 1);

        try {
            transaksi.deleteTransaksi(id_karyawan, id_proyek);
            loadTransaksi();
            JOptionPane.showMessageDialog(null, "Data berhasil dihapus", "Informasi", JOptionPane.INFORMATION_MESSAGE);
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Tidak dapat menghapus data, error: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            }// TODO add your handling code here:
    }//GEN-LAST:event_hpstransaksiActionPerformed

    private void cleartransaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cleartransaksiActionPerformed
        cbidkary.setSelectedIndex(0);
        cbidpry.setSelectedIndex(0);
        tfjobdesk.setText("");
        tfdur.setText("");// TODO add your handling code here:
    }//GEN-LAST:event_cleartransaksiActionPerformed

    private void edittransaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edittransaksiActionPerformed
        int selectedRow = TBTransaksi.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(null, "Pilih Baris yang akan di Ubah", "Peringatan", JOptionPane.WARNING_MESSAGE);
            return;
        }

        Object idValue = model3.getValueAt(selectedRow, 0);

        if (idValue == null || idValue.toString().isEmpty()) {
            JOptionPane.showMessageDialog(null, "ID Tidak valid atau kosong", "Peringatan", JOptionPane.WARNING_MESSAGE);
            return;
        }

        try {
            int kategori1 = Integer.parseInt(cbidkary.getSelectedItem().toString().split(" | ")[0]);
            int kategori2 = Integer.parseInt(cbidpry.getSelectedItem().toString().split(" | ")[0]);
            String peran = tfjobdesk.getText();
            String durasi = tfdur.getText();

            transaksi trs = new transaksi(kategori1, kategori2, peran, durasi);

            // Mengupdate data proyek di database
            try {
                transaksi.updateTransaksi(trs);
                loadTransaksi();
                JOptionPane.showMessageDialog(null, "Data berhasil diubah", "Informasi", JOptionPane.INFORMATION_MESSAGE);
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(null, "Tidak dapat mengubah data, error: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            }
        } catch (NumberFormatException e) {
            System.out.println("ID atau Durasi tidak valid: " + e.getMessage());
        }// TODO add your handling code here:
    }//GEN-LAST:event_edittransaksiActionPerformed

    private void exittransaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exittransaksiActionPerformed
        this.dispose();
    // TODO add your handling code here:
    }//GEN-LAST:event_exittransaksiActionPerformed

    private void tfdurasiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfdurasiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfdurasiActionPerformed
    public void loadTransaksi() {
        model3.setRowCount(0);
        try {
            List<transaksi> list_transaksi = transaksi.getAllTransaksi();
            
            for (transaksi trs: list_transaksi) {
                model3.addRow(
                    new Object[]{
                       trs.getIdKaryawan(),
                       trs.getIdProyek(),
                       trs.getPeran(),
                       trs.getDurasi()
                    }
            );
        }
            
        TBTransaksi.setModel(model3);
        
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Tidak dapat memuat data, error: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mod5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mod5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mod5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mod5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mod5().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TBKaryawan;
    private javax.swing.JTable TBProyek;
    private javax.swing.JTable TBTransaksi;
    private javax.swing.JButton btnclearkary;
    private javax.swing.JButton btneditkary;
    private javax.swing.JButton btnexitkary;
    private javax.swing.JButton btnhpskary;
    private javax.swing.JButton btntmbhkary;
    private javax.swing.JComboBox<String> cbdepart;
    private javax.swing.JComboBox<String> cbidkary;
    private javax.swing.JComboBox<String> cbidpry;
    private javax.swing.JComboBox<String> cbjabatan;
    private javax.swing.JButton clearproyek;
    private javax.swing.JButton cleartransaksi;
    private javax.swing.JButton editproyek;
    private javax.swing.JButton edittransaksi;
    private javax.swing.JButton exitproyek;
    private javax.swing.JButton exittransaksi;
    private javax.swing.JButton hpsproyek;
    private javax.swing.JButton hpstransaksi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField tfdur;
    private javax.swing.JTextField tfdurasi;
    private javax.swing.JTextField tfidkary;
    public javax.swing.JTextField tfidpry;
    private javax.swing.JTextField tfjobdesk;
    private javax.swing.JTextField tfnmkary;
    private javax.swing.JTextField tfnmpry;
    private javax.swing.JButton tmbhproyek;
    private javax.swing.JButton tmbhtransaksi;
    // End of variables declaration//GEN-END:variables

   

}
