

import java.awt.event.ActionListener;
import java.sql.SQLException;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author sindy
 */
public class App extends javax.swing.JFrame {
    private DefaultTableModel model1;
    private DefaultTableModel model2;
    private DefaultTableModel model3;
    private TB_Karyawan Karyawan = new TB_Karyawan();
    private TB_Proyek Proyek = new TB_Proyek();
    private TB_Transaksi Transaksi = new TB_Transaksi();
    /**
     * Creates new form App
     */
    public App() {
        initComponents();
        model1 = new DefaultTableModel(new String[]{"ID", "Nama", "Jabatan", "Dapartemen"}, 0);
        model2 = new DefaultTableModel(new String[]{"ID", "Durasi", "Nama_Proyek"}, 0);
        model3 = new DefaultTableModel(new String[]{"ID Karyawan", "ID Proyek", "Peran", "Durasi"}, 0);
        loadDataKaryawan();
        loadDataProyek();
        loadDataTransaksi();
        
    TabelKaryawan.getSelectionModel().addListSelectionListener(event -> {
        int selectedRow = TabelKaryawan.getSelectedRow();
        if (selectedRow != -1) {
            idKaryawan.setText(model1.getValueAt(selectedRow, 0).toString());
            NamaKaryawan.setText(model1.getValueAt(selectedRow, 1).toString());
            JabatanKaryawan.setText(model1.getValueAt(selectedRow, 2).toString());
            DapartemenKaryawan.setText(model1.getValueAt(selectedRow, 3).toString());
        }
    });
    
    TabelProyek.getSelectionModel().addListSelectionListener(event -> {
        int selectedRow = TabelProyek.getSelectedRow();
        if (selectedRow != -1) {
            idProyek.setText(model2.getValueAt(selectedRow, 0).toString());
            Durasi.setText(model2.getValueAt(selectedRow, 1).toString());
            NamaProyek.setText(model2.getValueAt(selectedRow, 2).toString());
        }
    });
    
    TabelTransaksi.getSelectionModel().addListSelectionListener(event -> {
        int selectedRow = TabelTransaksi.getSelectedRow();
        if (selectedRow != -1) {
            PilihanKaryawan.setSelectedItem(model3.getValueAt(selectedRow, 0).toString());
            PilihanProyek.setSelectedItem(model3.getValueAt(selectedRow, 1).toString());
            Peran.setText(model3.getValueAt(selectedRow, 2).toString());
            InputDurasi.setText(model3.getValueAt(selectedRow, 3).toString());
        }
    });
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        EditKaryawan = new javax.swing.JButton();
        TambahKaryawan = new javax.swing.JButton();
        HapusKaryawan = new javax.swing.JButton();
        ResetKaryawan = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TabelKaryawan = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        NamaKaryawan = new javax.swing.JTextField();
        JabatanKaryawan = new javax.swing.JTextField();
        DapartemenKaryawan = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        idKaryawan = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        EditProyek = new javax.swing.JButton();
        TambahProyek = new javax.swing.JButton();
        HapusProyek = new javax.swing.JButton();
        ResetProyek = new javax.swing.JButton();
        jPanel11 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        TabelProyek = new javax.swing.JTable();
        jLabel11 = new javax.swing.JLabel();
        NamaProyek = new javax.swing.JTextField();
        LabelDurasi = new javax.swing.JLabel();
        Durasi = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        idProyek = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        PilihanKaryawan = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        PilihanProyek = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        InputDurasi = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        Peran = new javax.swing.JTextField();
        jPanel14 = new javax.swing.JPanel();
        EditTransaksi = new javax.swing.JButton();
        TambahTransaksi = new javax.swing.JButton();
        HapusTransaksi = new javax.swing.JButton();
        ResetTransaksi = new javax.swing.JButton();
        jPanel15 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        TabelTransaksi = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("APLIKASI MANAJEMEN KARYAWAN DAN PROYEK");

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jTabbedPane1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel3.setBackground(new java.awt.Color(255, 204, 204));
        jPanel3.setLayout(new java.awt.BorderLayout());

        jPanel6.setBackground(new java.awt.Color(0, 102, 102));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("INFORMASI KARYAWAN");
        jPanel6.add(jLabel2);

        jPanel3.add(jPanel6, java.awt.BorderLayout.PAGE_START);

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setLayout(new java.awt.GridLayout(1, 0));

        EditKaryawan.setText("Edit");
        EditKaryawan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditKaryawanActionPerformed(evt);
            }
        });
        jPanel7.add(EditKaryawan);

        TambahKaryawan.setText("Tambah");
        TambahKaryawan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TambahKaryawanActionPerformed(evt);
            }
        });
        jPanel7.add(TambahKaryawan);

        HapusKaryawan.setText("Hapus");
        HapusKaryawan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HapusKaryawanActionPerformed(evt);
            }
        });
        jPanel7.add(HapusKaryawan);

        ResetKaryawan.setText("Reset Form");
        ResetKaryawan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResetKaryawanActionPerformed(evt);
            }
        });
        jPanel7.add(ResetKaryawan);

        jPanel3.add(jPanel7, java.awt.BorderLayout.PAGE_END);

        jPanel8.setBackground(new java.awt.Color(0, 102, 102));

        TabelKaryawan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Nama", "Jabatan", "Dapartemen"
            }
        ));
        jScrollPane1.setViewportView(TabelKaryawan);

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Nama:");

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Jabatan:");

        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Dapartemen:");

        JabatanKaryawan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JabatanKaryawanActionPerformed(evt);
            }
        });

        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("id:");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(idKaryawan, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel8)
                            .addComponent(NamaKaryawan, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JabatanKaryawan, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(5, 5, 5)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(DapartemenKaryawan, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 710, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel8)
                        .addComponent(jLabel9)
                        .addComponent(jLabel12)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NamaKaryawan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JabatanKaryawan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DapartemenKaryawan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(idKaryawan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        jPanel3.add(jPanel8, java.awt.BorderLayout.CENTER);

        jTabbedPane1.addTab("Karyawan", jPanel3);

        jPanel4.setLayout(new java.awt.BorderLayout());

        jPanel9.setBackground(new java.awt.Color(0, 0, 102));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("INFORMASI PROYEK");
        jPanel9.add(jLabel3);

        jPanel4.add(jPanel9, java.awt.BorderLayout.PAGE_START);

        jPanel10.setBackground(new java.awt.Color(255, 255, 255));
        jPanel10.setLayout(new java.awt.GridLayout(1, 0));

        EditProyek.setText("Edit");
        EditProyek.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditProyekActionPerformed(evt);
            }
        });
        jPanel10.add(EditProyek);

        TambahProyek.setText("Tambah");
        TambahProyek.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TambahProyekActionPerformed(evt);
            }
        });
        jPanel10.add(TambahProyek);

        HapusProyek.setText("Hapus");
        HapusProyek.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HapusProyekActionPerformed(evt);
            }
        });
        jPanel10.add(HapusProyek);

        ResetProyek.setText("Reset Form");
        ResetProyek.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResetProyekActionPerformed(evt);
            }
        });
        jPanel10.add(ResetProyek);

        jPanel4.add(jPanel10, java.awt.BorderLayout.PAGE_END);

        jPanel11.setBackground(new java.awt.Color(0, 0, 102));

        TabelProyek.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID", "Durasi", "Nama Proyek"
            }
        ));
        jScrollPane2.setViewportView(TabelProyek);

        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Nama Proyek:");

        LabelDurasi.setForeground(new java.awt.Color(255, 255, 255));
        LabelDurasi.setText("Durasi Pengerjaan:");

        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("id:");

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel11Layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addComponent(idProyek, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LabelDurasi, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Durasi, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(NamaProyek, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 708, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Durasi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(idProyek, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(LabelDurasi))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(NamaProyek, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        jPanel4.add(jPanel11, java.awt.BorderLayout.CENTER);

        jTabbedPane1.addTab("Proyek", jPanel4);

        jPanel5.setLayout(new java.awt.BorderLayout());

        jPanel12.setBackground(new java.awt.Color(102, 0, 102));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("TRANSAKSI PROYEK");
        jPanel12.add(jLabel4);

        jPanel5.add(jPanel12, java.awt.BorderLayout.PAGE_START);

        jPanel13.setBackground(new java.awt.Color(102, 0, 102));

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Karyawan:");

        PilihanKaryawan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- Karyawan --" }));

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Proyek:");

        PilihanProyek.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- Proyek --" }));

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Durasi (Minggu):");

        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Peran: ");

        Peran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PeranActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addComponent(PilihanKaryawan, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(PilihanProyek, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(InputDurasi, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Peran, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(105, 105, 105)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(106, 106, 106)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(51, 51, 51)
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(114, Short.MAX_VALUE))
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PilihanKaryawan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PilihanProyek, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(InputDurasi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Peran, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel5.add(jPanel13, java.awt.BorderLayout.PAGE_END);

        jPanel14.setBackground(new java.awt.Color(102, 0, 102));

        EditTransaksi.setText("Edit");
        EditTransaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditTransaksiActionPerformed(evt);
            }
        });

        TambahTransaksi.setText("Tambah");
        TambahTransaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TambahTransaksiActionPerformed(evt);
            }
        });

        HapusTransaksi.setText("Hapus");
        HapusTransaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HapusTransaksiActionPerformed(evt);
            }
        });

        ResetTransaksi.setText("Reset Form");
        ResetTransaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResetTransaksiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(HapusTransaksi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(EditTransaksi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(TambahTransaksi, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE)
                    .addComponent(ResetTransaksi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(10, Short.MAX_VALUE))
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(EditTransaksi)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TambahTransaksi)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(HapusTransaksi)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ResetTransaksi)
                .addContainerGap(188, Short.MAX_VALUE))
        );

        jPanel5.add(jPanel14, java.awt.BorderLayout.LINE_END);

        jPanel15.setBackground(new java.awt.Color(102, 0, 102));

        TabelTransaksi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID Karyawan", "ID Proyek", "Peran", "Durasi"
            }
        ));
        jScrollPane3.setViewportView(TabelTransaksi);

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 619, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 304, Short.MAX_VALUE)
        );

        jPanel5.add(jPanel15, java.awt.BorderLayout.CENTER);

        jTabbedPane1.addTab("Transaksi", jPanel5);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 425, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(178, 178, 178)
                .addComponent(jLabel1)
                .addContainerGap(225, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JabatanKaryawanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JabatanKaryawanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JabatanKaryawanActionPerformed

    private void TambahKaryawanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TambahKaryawanActionPerformed
        // TODO add your handling code here:
        String val_id = idKaryawan.getText();
        String val_nama = NamaKaryawan.getText();
        String val_jabatan = JabatanKaryawan.getText();
        String val_dapartemen = DapartemenKaryawan.getText();
        
        BarangKaryawan brg = new BarangKaryawan(
        0,
        val_nama,
        val_jabatan,
        val_dapartemen
        );
        
        try {
            Karyawan.InsertKaryawan(brg);
            loadDataKaryawan(); 
            JOptionPane.showMessageDialog(null, "Data berhasil disimpan", "Informasi", JOptionPane.INFORMATION_MESSAGE);
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Tidak dapat menambahkan data, error: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_TambahKaryawanActionPerformed

    private void HapusKaryawanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HapusKaryawanActionPerformed
        // TODO add your handling code here:
        int selectedRow = TabelKaryawan.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(null, "Piih baris yang akan dihapus", "Peringatan", JOptionPane.WARNING_MESSAGE);
            return;
        }

        int id = (int) model1.getValueAt(selectedRow, 0);

        try {
            Karyawan.deleteKaryawan(id);
            loadDataKaryawan();
            JOptionPane.showMessageDialog(null, "Data berhasil dihapus", "Informasi", JOptionPane.INFORMATION_MESSAGE);
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Tidak dapat menghapus data, error: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            }
    }//GEN-LAST:event_HapusKaryawanActionPerformed

    private void EditKaryawanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditKaryawanActionPerformed
        // TODO add your handling code here:
        int selectedRow = TabelKaryawan.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(null, "Pilih Baris yang akan diubah", "Peringatan", JOptionPane.WARNING_MESSAGE);
            return;
        }

        // Mendapatkan nilai ID dari tabel dan memeriksa apakah nilainya tidak kosong
        Object idValue = model1.getValueAt(selectedRow, 0);
        if (idValue == null || idValue.toString().isEmpty()) {
            JOptionPane.showMessageDialog(null, "ID tidak valid atau kosong.", "Peringatan", JOptionPane.WARNING_MESSAGE);
            return;
        }

        try {
            int id = Integer.parseInt(idValue.toString());
            String nama = NamaKaryawan.getText();
            String jabatan = JabatanKaryawan.getText();
            String dapartemen = DapartemenKaryawan.getText();

            // Membuat objek Barang dengan data yang diperbarui
            BarangKaryawan barang = new BarangKaryawan(id, nama, jabatan, dapartemen);

            // Mengupdate data barang
            try {
                Karyawan.updateKaryawan(barang);
                loadDataKaryawan(); 
                JOptionPane.showMessageDialog(null, "Data berhasil diubah", "Informasi", JOptionPane.INFORMATION_MESSAGE);
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(null, "Tidak dapat mengubah data, error: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            }
        } catch (NumberFormatException e) {
            System.out.println("ID tidak valid: " + e.getMessage());
        }
    }//GEN-LAST:event_EditKaryawanActionPerformed

    private void TambahProyekActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TambahProyekActionPerformed
        // TODO add your handling code here:
        String val_id = idProyek.getText();
        String val_durasi = Durasi.getText();
        String val_nama_proyek = NamaProyek.getText();
        
        int durasi = 0;
        
        try {
            // Konversi val_durasi ke int jika tidak kosong
            if (!val_durasi.isEmpty()) {
                durasi = Integer.parseInt(val_durasi);
            } else {
                JOptionPane.showMessageDialog(null, "Durasi tidak boleh kosong.", "Peringatan", JOptionPane.WARNING_MESSAGE);
                return;
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Durasi harus berupa angka valid, error: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        BarangProyek barang = new BarangProyek(
            0,             
            durasi,        
            val_nama_proyek
        );

        try {
            Proyek.InsertProyek(barang);
            loadDataProyek();
            JOptionPane.showMessageDialog(null, "Data Berhasil Disimpan", "Informasi", JOptionPane.INFORMATION_MESSAGE);
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Tidak dapat menambahkan proyek, error: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_TambahProyekActionPerformed

    private void EditProyekActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditProyekActionPerformed
        // TODO add your handling code here:
        int selectedRow = TabelProyek.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(null, "Pilih baris yang akan diubah", "Peringatan", JOptionPane.WARNING_MESSAGE);
            return;
        }

        Object idValue = model2.getValueAt(selectedRow, 0);

        if (idValue == null || idValue.toString().isEmpty()) {
            JOptionPane.showMessageDialog(null, "ID tidak valid atau kosong.", "Peringatan", JOptionPane.WARNING_MESSAGE);
            return;
        }

        try {
            int id = Integer.parseInt(idValue.toString());
            int durasi = Integer.parseInt(Durasi.getText());  
            String nama_proyek = NamaProyek.getText();


            BarangProyek barang = new BarangProyek(id, durasi, nama_proyek);

            // Mengupdate data proyek di database
            try {
                Proyek.updateProyek(barang);
                loadDataProyek();
                JOptionPane.showMessageDialog(null, "Data berhasil diubah", "Informasi", JOptionPane.INFORMATION_MESSAGE);
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(null, "Tidak dapat mengubah data, error: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            }
        } catch (NumberFormatException e) {
            System.out.println("ID atau Durasi tidak valid: " + e.getMessage());
        }
    }//GEN-LAST:event_EditProyekActionPerformed

    private void HapusProyekActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HapusProyekActionPerformed
        // TODO add your handling code here:
        int selectedRow = TabelProyek.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(null, "Pilih Baris yang akan dihapus", "Peringatan", JOptionPane.WARNING_MESSAGE);
            return;
        }

        int id = (int) model2.getValueAt(selectedRow, 0);

        try {
            Proyek.deleteProyek(id);
            loadDataProyek();
            JOptionPane.showMessageDialog(null, "Data berhasil dihapus", "Informasi", JOptionPane.INFORMATION_MESSAGE);
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Tidak dapat menghapus data, error: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            }
    }//GEN-LAST:event_HapusProyekActionPerformed

    private void ResetKaryawanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResetKaryawanActionPerformed
        // TODO add your handling code here:
        NamaKaryawan.setText("");
        JabatanKaryawan.setText("");
        DapartemenKaryawan.setText("");
        idKaryawan.setText("");
    }//GEN-LAST:event_ResetKaryawanActionPerformed

    private void ResetProyekActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResetProyekActionPerformed
        // TODO add your handling code here:
        NamaProyek.setText("");
        Durasi.setText("");
        idProyek.setText("");
    }//GEN-LAST:event_ResetProyekActionPerformed

    private void EditTransaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditTransaksiActionPerformed
        // TODO add your handling code here:
        int selectedRow = TabelTransaksi.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(null, "Pilih Baris yang akan di Ubah", "Peringatan", JOptionPane.WARNING_MESSAGE);
            return;
        }

        Object idValue = model3.getValueAt(selectedRow, 0);

        if (idValue == null || idValue.toString().isEmpty()) {
            JOptionPane.showMessageDialog(null, "ID Tidak valid atau kosong", "Peringatan", JOptionPane.WARNING_MESSAGE);
            return;
        }

        try {
            int kategori1 = Integer.parseInt(PilihanKaryawan.getSelectedItem().toString().split(" - ")[0]);
            int kategori2 = Integer.parseInt(PilihanProyek.getSelectedItem().toString().split(" - ")[0]);
            String peran = Peran.getText();
            String durasi = InputDurasi.getText();

            BarangTransaksi barang = new BarangTransaksi(kategori1, kategori2, peran, durasi);

            // Mengupdate data proyek di database
            try {
                Transaksi.updateTransaksi(barang);
                loadDataTransaksi();
                JOptionPane.showMessageDialog(null, "Data berhasil diubah", "Informasi", JOptionPane.INFORMATION_MESSAGE);
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(null, "Tidak dapat mengubah data, error: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            }
        } catch (NumberFormatException e) {
            System.out.println("ID atau Durasi tidak valid: " + e.getMessage());
        }
    }//GEN-LAST:event_EditTransaksiActionPerformed

    private void TambahTransaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TambahTransaksiActionPerformed
        // TODO add your handling code here:
        String val_idkaryawan = PilihanKaryawan.getSelectedItem().toString().split(" - ")[0];
        String val_idproyek = PilihanProyek.getSelectedItem().toString().split(" - ")[0];
        String val_peran = Peran.getText();
        String val_durasi = InputDurasi.getText();

        int idKaryawan = Integer.parseInt(val_idkaryawan);
        int idProyek = Integer.parseInt(val_idproyek);

        BarangTransaksi brg = new BarangTransaksi(
            idKaryawan,
            idProyek,
            val_peran,
            val_durasi
        );

        try {
            Transaksi.InsertTransaksi(brg);
            loadDataTransaksi(); 
            JOptionPane.showMessageDialog(null, "Data berhasil disimpan", "Informasi", JOptionPane.INFORMATION_MESSAGE);
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Tidak dapat menambahkan data, error: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_TambahTransaksiActionPerformed

    private void PeranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PeranActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PeranActionPerformed

    private void HapusTransaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HapusTransaksiActionPerformed
        // TODO add your handling code here:
        int selectedRow = TabelTransaksi.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(null, "Pilih Baris yang akan dihapus", "Peringatan", JOptionPane.WARNING_MESSAGE);
            return;
        }

        int id_karyawan = (int) model3.getValueAt(selectedRow, 0);

        try {
            Transaksi.deleteTransaksi(id_karyawan);
            loadDataTransaksi();
            JOptionPane.showMessageDialog(null, "Data berhasil dihapus", "Informasi", JOptionPane.INFORMATION_MESSAGE);
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Tidak dapat menghapus data, error: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            }
    }//GEN-LAST:event_HapusTransaksiActionPerformed

    private void ResetTransaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResetTransaksiActionPerformed
        // TODO add your handling code here:
        PilihanKaryawan.setSelectedIndex(0);
        PilihanProyek.setSelectedIndex(0);
        Peran.setText("");
        InputDurasi.setText("");
    }//GEN-LAST:event_ResetTransaksiActionPerformed

    /**
     * @param args the command line arguments
     */
   
    public void loadDataKaryawan() {
        model1.setRowCount(0);
        PilihanKaryawan.removeAllItems();
        PilihanKaryawan.addItem("-- Karyawan --");
        try {
            List<BarangKaryawan> list_karyawan = Karyawan.getAllKaryawan();
            
            for (BarangKaryawan brg: list_karyawan) {
                model1.addRow(
                    new Object[]{
                       brg.getId(),
                       brg.getNama(),
                       brg.getJabatan(),
                       brg.getDapartemen()
                    }
            );
                
            PilihanKaryawan.addItem(brg.getId() + " - " + brg.getNama());
        }
            
        TabelKaryawan.setModel(model1);
        
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Tidak dapat memuat data, error: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    public void loadDataProyek() {
    model2.setRowCount(0);
    PilihanProyek.removeAllItems();
    PilihanProyek.addItem("-- Proyek --");


    try {
        List<BarangProyek> list_proyek = Proyek.getAllProyek();

        for (BarangProyek brg : list_proyek) {
            model2.addRow(new Object[]{
                brg.getId(),
                brg.getDurasi(),
                brg.getNamaProyek()
            });

            PilihanProyek.addItem(brg.getId() + " - " + brg.getNamaProyek());
        }

        TabelProyek.setModel(model2);
        
        for (ActionListener al : PilihanProyek.getActionListeners()) {
            PilihanProyek.removeActionListener(al);
        }

        PilihanProyek.addActionListener(e -> {
            // Ambil ID proyek dari item yang dipilih
            String selectedItem = (String) PilihanProyek.getSelectedItem();
            if (selectedItem != null) {
                String idProyek = selectedItem.split(" - ")[0]; 

                // Cari durasi proyek yang sesuai
                for (BarangProyek brg : list_proyek) {
                    if (String.valueOf(brg.getId()).equals(idProyek)) {
                        InputDurasi.setText(String.valueOf(brg.getDurasi()));
                        break;
                    }
                }
            }
        });

    } catch (SQLException e) {
        JOptionPane.showMessageDialog(null, "Tidak dapat memuat data, error: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
    }
}
    
    public void loadDataTransaksi() {
        model3.setRowCount(0);
        try {
            List<BarangTransaksi> list_transaksi = Transaksi.getAllTransaksi();
            
            for (BarangTransaksi brg: list_transaksi) {
                model3.addRow(
                    new Object[]{
                       brg.getIdKaryawan(),
                       brg.getIdProyek(),
                       brg.getPeran(),
                       brg.getDurasi()
                    }
            );
        }
            
        TabelTransaksi.setModel(model3);
        
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Tidak dapat memuat data, error: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new App().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField DapartemenKaryawan;
    private javax.swing.JTextField Durasi;
    private javax.swing.JButton EditKaryawan;
    private javax.swing.JButton EditProyek;
    private javax.swing.JButton EditTransaksi;
    private javax.swing.JButton HapusKaryawan;
    private javax.swing.JButton HapusProyek;
    private javax.swing.JButton HapusTransaksi;
    private javax.swing.JTextField InputDurasi;
    private javax.swing.JTextField JabatanKaryawan;
    private javax.swing.JLabel LabelDurasi;
    private javax.swing.JTextField NamaKaryawan;
    private javax.swing.JTextField NamaProyek;
    private javax.swing.JTextField Peran;
    private javax.swing.JComboBox<String> PilihanKaryawan;
    private javax.swing.JComboBox<String> PilihanProyek;
    private javax.swing.JButton ResetKaryawan;
    private javax.swing.JButton ResetProyek;
    private javax.swing.JButton ResetTransaksi;
    private javax.swing.JTable TabelKaryawan;
    private javax.swing.JTable TabelProyek;
    private javax.swing.JTable TabelTransaksi;
    private javax.swing.JButton TambahKaryawan;
    private javax.swing.JButton TambahProyek;
    private javax.swing.JButton TambahTransaksi;
    private javax.swing.JTextField idKaryawan;
    private javax.swing.JTextField idProyek;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
